// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newApplication(db *gorm.DB, opts ...gen.DOOption) application {
	_application := application{}

	_application.applicationDo.UseDB(db, opts...)
	_application.applicationDo.UseModel(&model.Application{})

	tableName := _application.applicationDo.TableName()
	_application.ALL = field.NewAsterisk(tableName)
	_application.ID = field.NewInt64(tableName, "id")
	_application.AppName = field.NewString(tableName, "app_name")
	_application.Secret = field.NewString(tableName, "secret")
	_application.AppNo = field.NewString(tableName, "app_no")
	_application.MchNo = field.NewString(tableName, "mch_no")
	_application.Desc = field.NewString(tableName, "desc")
	_application.PaymentTitle = field.NewString(tableName, "payment_title")
	_application.PayIcon = field.NewString(tableName, "pay_icon")
	_application.Status = field.NewInt64(tableName, "status")
	_application.IsCustomerDomain = field.NewInt64(tableName, "is_customer_domain")
	_application.CustomerDomain = field.NewString(tableName, "customer_domain")
	_application.ProxyHost = field.NewString(tableName, "proxy_host")
	_application.ProxyPort = field.NewInt64(tableName, "proxy_port")
	_application.ProxyUser = field.NewString(tableName, "proxy_user")
	_application.ProxyPwd = field.NewString(tableName, "proxy_pwd")
	_application.MultiChannel = field.NewInt64(tableName, "multi_channel")
	_application.AccountVersion = field.NewString(tableName, "account_version")
	_application.CreatedAt = field.NewTime(tableName, "created_at")
	_application.UpdatedAt = field.NewTime(tableName, "updated_at")

	_application.fillFieldMap()

	return _application
}

// application 公司信息
type application struct {
	applicationDo applicationDo

	ALL              field.Asterisk
	ID               field.Int64
	AppName          field.String // 应用名字
	Secret           field.String // 应用秘密
	AppNo            field.String // 应用编号
	MchNo            field.String // 商户编号
	Desc             field.String // 应用描述
	PaymentTitle     field.String // 支付的tiltle
	PayIcon          field.String // 支付的icon
	Status           field.Int64  // 2 停用 1 正常
	IsCustomerDomain field.Int64  // 是否自定义域名方式
	CustomerDomain   field.String // 自定义域名
	ProxyHost        field.String
	ProxyPort        field.Int64  // 端口
	ProxyUser        field.String // 用户名
	ProxyPwd         field.String // 密码
	MultiChannel     field.Int64  // 是否支持单一channel配置多个
	AccountVersion   field.String // 支付账户版本号，每次payment_account都会更新更改版本号
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (a application) Table(newTableName string) *application {
	a.applicationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a application) As(alias string) *application {
	a.applicationDo.DO = *(a.applicationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *application) updateTableName(table string) *application {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.AppName = field.NewString(table, "app_name")
	a.Secret = field.NewString(table, "secret")
	a.AppNo = field.NewString(table, "app_no")
	a.MchNo = field.NewString(table, "mch_no")
	a.Desc = field.NewString(table, "desc")
	a.PaymentTitle = field.NewString(table, "payment_title")
	a.PayIcon = field.NewString(table, "pay_icon")
	a.Status = field.NewInt64(table, "status")
	a.IsCustomerDomain = field.NewInt64(table, "is_customer_domain")
	a.CustomerDomain = field.NewString(table, "customer_domain")
	a.ProxyHost = field.NewString(table, "proxy_host")
	a.ProxyPort = field.NewInt64(table, "proxy_port")
	a.ProxyUser = field.NewString(table, "proxy_user")
	a.ProxyPwd = field.NewString(table, "proxy_pwd")
	a.MultiChannel = field.NewInt64(table, "multi_channel")
	a.AccountVersion = field.NewString(table, "account_version")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *application) WithContext(ctx context.Context) IApplicationDo {
	return a.applicationDo.WithContext(ctx)
}

func (a application) TableName() string { return a.applicationDo.TableName() }

func (a application) Alias() string { return a.applicationDo.Alias() }

func (a application) Columns(cols ...field.Expr) gen.Columns { return a.applicationDo.Columns(cols...) }

func (a *application) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *application) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 19)
	a.fieldMap["id"] = a.ID
	a.fieldMap["app_name"] = a.AppName
	a.fieldMap["secret"] = a.Secret
	a.fieldMap["app_no"] = a.AppNo
	a.fieldMap["mch_no"] = a.MchNo
	a.fieldMap["desc"] = a.Desc
	a.fieldMap["payment_title"] = a.PaymentTitle
	a.fieldMap["pay_icon"] = a.PayIcon
	a.fieldMap["status"] = a.Status
	a.fieldMap["is_customer_domain"] = a.IsCustomerDomain
	a.fieldMap["customer_domain"] = a.CustomerDomain
	a.fieldMap["proxy_host"] = a.ProxyHost
	a.fieldMap["proxy_port"] = a.ProxyPort
	a.fieldMap["proxy_user"] = a.ProxyUser
	a.fieldMap["proxy_pwd"] = a.ProxyPwd
	a.fieldMap["multi_channel"] = a.MultiChannel
	a.fieldMap["account_version"] = a.AccountVersion
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a application) clone(db *gorm.DB) application {
	a.applicationDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a application) replaceDB(db *gorm.DB) application {
	a.applicationDo.ReplaceDB(db)
	return a
}

type applicationDo struct{ gen.DO }

type IApplicationDo interface {
	gen.SubQuery
	Debug() IApplicationDo
	WithContext(ctx context.Context) IApplicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApplicationDo
	WriteDB() IApplicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApplicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApplicationDo
	Not(conds ...gen.Condition) IApplicationDo
	Or(conds ...gen.Condition) IApplicationDo
	Select(conds ...field.Expr) IApplicationDo
	Where(conds ...gen.Condition) IApplicationDo
	Order(conds ...field.Expr) IApplicationDo
	Distinct(cols ...field.Expr) IApplicationDo
	Omit(cols ...field.Expr) IApplicationDo
	Join(table schema.Tabler, on ...field.Expr) IApplicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApplicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApplicationDo
	Group(cols ...field.Expr) IApplicationDo
	Having(conds ...gen.Condition) IApplicationDo
	Limit(limit int) IApplicationDo
	Offset(offset int) IApplicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApplicationDo
	Unscoped() IApplicationDo
	Create(values ...*model.Application) error
	CreateInBatches(values []*model.Application, batchSize int) error
	Save(values ...*model.Application) error
	First() (*model.Application, error)
	Take() (*model.Application, error)
	Last() (*model.Application, error)
	Find() ([]*model.Application, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Application, err error)
	FindInBatches(result *[]*model.Application, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Application) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApplicationDo
	Assign(attrs ...field.AssignExpr) IApplicationDo
	Joins(fields ...field.RelationField) IApplicationDo
	Preload(fields ...field.RelationField) IApplicationDo
	FirstOrInit() (*model.Application, error)
	FirstOrCreate() (*model.Application, error)
	FindByPage(offset int, limit int) (result []*model.Application, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApplicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a applicationDo) Debug() IApplicationDo {
	return a.withDO(a.DO.Debug())
}

func (a applicationDo) WithContext(ctx context.Context) IApplicationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a applicationDo) ReadDB() IApplicationDo {
	return a.Clauses(dbresolver.Read)
}

func (a applicationDo) WriteDB() IApplicationDo {
	return a.Clauses(dbresolver.Write)
}

func (a applicationDo) Session(config *gorm.Session) IApplicationDo {
	return a.withDO(a.DO.Session(config))
}

func (a applicationDo) Clauses(conds ...clause.Expression) IApplicationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a applicationDo) Returning(value interface{}, columns ...string) IApplicationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a applicationDo) Not(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a applicationDo) Or(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a applicationDo) Select(conds ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a applicationDo) Where(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a applicationDo) Order(conds ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a applicationDo) Distinct(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a applicationDo) Omit(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a applicationDo) Join(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a applicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a applicationDo) RightJoin(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a applicationDo) Group(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a applicationDo) Having(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a applicationDo) Limit(limit int) IApplicationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a applicationDo) Offset(offset int) IApplicationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a applicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApplicationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a applicationDo) Unscoped() IApplicationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a applicationDo) Create(values ...*model.Application) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a applicationDo) CreateInBatches(values []*model.Application, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a applicationDo) Save(values ...*model.Application) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a applicationDo) First() (*model.Application, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Application), nil
	}
}

func (a applicationDo) Take() (*model.Application, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Application), nil
	}
}

func (a applicationDo) Last() (*model.Application, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Application), nil
	}
}

func (a applicationDo) Find() ([]*model.Application, error) {
	result, err := a.DO.Find()
	return result.([]*model.Application), err
}

func (a applicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Application, err error) {
	buf := make([]*model.Application, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a applicationDo) FindInBatches(result *[]*model.Application, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a applicationDo) Attrs(attrs ...field.AssignExpr) IApplicationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a applicationDo) Assign(attrs ...field.AssignExpr) IApplicationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a applicationDo) Joins(fields ...field.RelationField) IApplicationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a applicationDo) Preload(fields ...field.RelationField) IApplicationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a applicationDo) FirstOrInit() (*model.Application, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Application), nil
	}
}

func (a applicationDo) FirstOrCreate() (*model.Application, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Application), nil
	}
}

func (a applicationDo) FindByPage(offset int, limit int) (result []*model.Application, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a applicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a applicationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a applicationDo) Delete(models ...*model.Application) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *applicationDo) withDO(do gen.Dao) *applicationDo {
	a.DO = *do.(*gen.DO)
	return a
}
