// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newEventProcessRecord(db *gorm.DB, opts ...gen.DOOption) eventProcessRecord {
	_eventProcessRecord := eventProcessRecord{}

	_eventProcessRecord.eventProcessRecordDo.UseDB(db, opts...)
	_eventProcessRecord.eventProcessRecordDo.UseModel(&model.EventProcessRecord{})

	tableName := _eventProcessRecord.eventProcessRecordDo.TableName()
	_eventProcessRecord.ALL = field.NewAsterisk(tableName)
	_eventProcessRecord.ID = field.NewInt64(tableName, "id")
	_eventProcessRecord.EventID = field.NewString(tableName, "event_id")
	_eventProcessRecord.EventType = field.NewString(tableName, "event_type")
	_eventProcessRecord.ProcessedAt = field.NewInt64(tableName, "processed_at")
	_eventProcessRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_eventProcessRecord.Consumer = field.NewString(tableName, "consumer")

	_eventProcessRecord.fillFieldMap()

	return _eventProcessRecord
}

// eventProcessRecord 支付事件处理记录表
type eventProcessRecord struct {
	eventProcessRecordDo eventProcessRecordDo

	ALL         field.Asterisk
	ID          field.Int64
	EventID     field.String // 事件唯一ID
	EventType   field.String // 事件唯一ID
	ProcessedAt field.Int64  // 处理时间,时间戳
	CreatedAt   field.Time
	Consumer    field.String // 消费者

	fieldMap map[string]field.Expr
}

func (e eventProcessRecord) Table(newTableName string) *eventProcessRecord {
	e.eventProcessRecordDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventProcessRecord) As(alias string) *eventProcessRecord {
	e.eventProcessRecordDo.DO = *(e.eventProcessRecordDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventProcessRecord) updateTableName(table string) *eventProcessRecord {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.EventID = field.NewString(table, "event_id")
	e.EventType = field.NewString(table, "event_type")
	e.ProcessedAt = field.NewInt64(table, "processed_at")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.Consumer = field.NewString(table, "consumer")

	e.fillFieldMap()

	return e
}

func (e *eventProcessRecord) WithContext(ctx context.Context) IEventProcessRecordDo {
	return e.eventProcessRecordDo.WithContext(ctx)
}

func (e eventProcessRecord) TableName() string { return e.eventProcessRecordDo.TableName() }

func (e eventProcessRecord) Alias() string { return e.eventProcessRecordDo.Alias() }

func (e eventProcessRecord) Columns(cols ...field.Expr) gen.Columns {
	return e.eventProcessRecordDo.Columns(cols...)
}

func (e *eventProcessRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventProcessRecord) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 6)
	e.fieldMap["id"] = e.ID
	e.fieldMap["event_id"] = e.EventID
	e.fieldMap["event_type"] = e.EventType
	e.fieldMap["processed_at"] = e.ProcessedAt
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["consumer"] = e.Consumer
}

func (e eventProcessRecord) clone(db *gorm.DB) eventProcessRecord {
	e.eventProcessRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventProcessRecord) replaceDB(db *gorm.DB) eventProcessRecord {
	e.eventProcessRecordDo.ReplaceDB(db)
	return e
}

type eventProcessRecordDo struct{ gen.DO }

type IEventProcessRecordDo interface {
	gen.SubQuery
	Debug() IEventProcessRecordDo
	WithContext(ctx context.Context) IEventProcessRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventProcessRecordDo
	WriteDB() IEventProcessRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventProcessRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventProcessRecordDo
	Not(conds ...gen.Condition) IEventProcessRecordDo
	Or(conds ...gen.Condition) IEventProcessRecordDo
	Select(conds ...field.Expr) IEventProcessRecordDo
	Where(conds ...gen.Condition) IEventProcessRecordDo
	Order(conds ...field.Expr) IEventProcessRecordDo
	Distinct(cols ...field.Expr) IEventProcessRecordDo
	Omit(cols ...field.Expr) IEventProcessRecordDo
	Join(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo
	Group(cols ...field.Expr) IEventProcessRecordDo
	Having(conds ...gen.Condition) IEventProcessRecordDo
	Limit(limit int) IEventProcessRecordDo
	Offset(offset int) IEventProcessRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventProcessRecordDo
	Unscoped() IEventProcessRecordDo
	Create(values ...*model.EventProcessRecord) error
	CreateInBatches(values []*model.EventProcessRecord, batchSize int) error
	Save(values ...*model.EventProcessRecord) error
	First() (*model.EventProcessRecord, error)
	Take() (*model.EventProcessRecord, error)
	Last() (*model.EventProcessRecord, error)
	Find() ([]*model.EventProcessRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventProcessRecord, err error)
	FindInBatches(result *[]*model.EventProcessRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventProcessRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventProcessRecordDo
	Assign(attrs ...field.AssignExpr) IEventProcessRecordDo
	Joins(fields ...field.RelationField) IEventProcessRecordDo
	Preload(fields ...field.RelationField) IEventProcessRecordDo
	FirstOrInit() (*model.EventProcessRecord, error)
	FirstOrCreate() (*model.EventProcessRecord, error)
	FindByPage(offset int, limit int) (result []*model.EventProcessRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventProcessRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventProcessRecordDo) Debug() IEventProcessRecordDo {
	return e.withDO(e.DO.Debug())
}

func (e eventProcessRecordDo) WithContext(ctx context.Context) IEventProcessRecordDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventProcessRecordDo) ReadDB() IEventProcessRecordDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventProcessRecordDo) WriteDB() IEventProcessRecordDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventProcessRecordDo) Session(config *gorm.Session) IEventProcessRecordDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventProcessRecordDo) Clauses(conds ...clause.Expression) IEventProcessRecordDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventProcessRecordDo) Returning(value interface{}, columns ...string) IEventProcessRecordDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventProcessRecordDo) Not(conds ...gen.Condition) IEventProcessRecordDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventProcessRecordDo) Or(conds ...gen.Condition) IEventProcessRecordDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventProcessRecordDo) Select(conds ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventProcessRecordDo) Where(conds ...gen.Condition) IEventProcessRecordDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventProcessRecordDo) Order(conds ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventProcessRecordDo) Distinct(cols ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventProcessRecordDo) Omit(cols ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventProcessRecordDo) Join(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventProcessRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventProcessRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventProcessRecordDo) Group(cols ...field.Expr) IEventProcessRecordDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventProcessRecordDo) Having(conds ...gen.Condition) IEventProcessRecordDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventProcessRecordDo) Limit(limit int) IEventProcessRecordDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventProcessRecordDo) Offset(offset int) IEventProcessRecordDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventProcessRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventProcessRecordDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventProcessRecordDo) Unscoped() IEventProcessRecordDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventProcessRecordDo) Create(values ...*model.EventProcessRecord) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventProcessRecordDo) CreateInBatches(values []*model.EventProcessRecord, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventProcessRecordDo) Save(values ...*model.EventProcessRecord) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventProcessRecordDo) First() (*model.EventProcessRecord, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventProcessRecord), nil
	}
}

func (e eventProcessRecordDo) Take() (*model.EventProcessRecord, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventProcessRecord), nil
	}
}

func (e eventProcessRecordDo) Last() (*model.EventProcessRecord, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventProcessRecord), nil
	}
}

func (e eventProcessRecordDo) Find() ([]*model.EventProcessRecord, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventProcessRecord), err
}

func (e eventProcessRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventProcessRecord, err error) {
	buf := make([]*model.EventProcessRecord, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventProcessRecordDo) FindInBatches(result *[]*model.EventProcessRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventProcessRecordDo) Attrs(attrs ...field.AssignExpr) IEventProcessRecordDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventProcessRecordDo) Assign(attrs ...field.AssignExpr) IEventProcessRecordDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventProcessRecordDo) Joins(fields ...field.RelationField) IEventProcessRecordDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventProcessRecordDo) Preload(fields ...field.RelationField) IEventProcessRecordDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventProcessRecordDo) FirstOrInit() (*model.EventProcessRecord, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventProcessRecord), nil
	}
}

func (e eventProcessRecordDo) FirstOrCreate() (*model.EventProcessRecord, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventProcessRecord), nil
	}
}

func (e eventProcessRecordDo) FindByPage(offset int, limit int) (result []*model.EventProcessRecord, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventProcessRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventProcessRecordDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventProcessRecordDo) Delete(models ...*model.EventProcessRecord) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventProcessRecordDo) withDO(do gen.Dao) *eventProcessRecordDo {
	e.DO = *do.(*gen.DO)
	return e
}
