// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	Application            *application
	EventProcessRecord     *eventProcessRecord
	Merchant               *merchant
	NotifyRecord           *notifyRecord
	PaymentAccount         *paymentAccount
	PaymentExpireRecord    *paymentExpireRecord
	PaymentMethod          *paymentMethod
	PaymentOrder           *paymentOrder
	PaymentOrderProduct    *paymentOrderProduct
	PaymentRequestLog      *paymentRequestLog
	RefundOrder            *refundOrder
	RefundOrderProduct     *refundOrderProduct
	RouterAccountStatistic *routerAccountStatistic
	Statistic              *statistic
	TradeStatistic         *tradeStatistic
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Application = &Q.Application
	EventProcessRecord = &Q.EventProcessRecord
	Merchant = &Q.Merchant
	NotifyRecord = &Q.NotifyRecord
	PaymentAccount = &Q.PaymentAccount
	PaymentExpireRecord = &Q.PaymentExpireRecord
	PaymentMethod = &Q.PaymentMethod
	PaymentOrder = &Q.PaymentOrder
	PaymentOrderProduct = &Q.PaymentOrderProduct
	PaymentRequestLog = &Q.PaymentRequestLog
	RefundOrder = &Q.RefundOrder
	RefundOrderProduct = &Q.RefundOrderProduct
	RouterAccountStatistic = &Q.RouterAccountStatistic
	Statistic = &Q.Statistic
	TradeStatistic = &Q.TradeStatistic
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		Application:            newApplication(db, opts...),
		EventProcessRecord:     newEventProcessRecord(db, opts...),
		Merchant:               newMerchant(db, opts...),
		NotifyRecord:           newNotifyRecord(db, opts...),
		PaymentAccount:         newPaymentAccount(db, opts...),
		PaymentExpireRecord:    newPaymentExpireRecord(db, opts...),
		PaymentMethod:          newPaymentMethod(db, opts...),
		PaymentOrder:           newPaymentOrder(db, opts...),
		PaymentOrderProduct:    newPaymentOrderProduct(db, opts...),
		PaymentRequestLog:      newPaymentRequestLog(db, opts...),
		RefundOrder:            newRefundOrder(db, opts...),
		RefundOrderProduct:     newRefundOrderProduct(db, opts...),
		RouterAccountStatistic: newRouterAccountStatistic(db, opts...),
		Statistic:              newStatistic(db, opts...),
		TradeStatistic:         newTradeStatistic(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Application            application
	EventProcessRecord     eventProcessRecord
	Merchant               merchant
	NotifyRecord           notifyRecord
	PaymentAccount         paymentAccount
	PaymentExpireRecord    paymentExpireRecord
	PaymentMethod          paymentMethod
	PaymentOrder           paymentOrder
	PaymentOrderProduct    paymentOrderProduct
	PaymentRequestLog      paymentRequestLog
	RefundOrder            refundOrder
	RefundOrderProduct     refundOrderProduct
	RouterAccountStatistic routerAccountStatistic
	Statistic              statistic
	TradeStatistic         tradeStatistic
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		Application:            q.Application.clone(db),
		EventProcessRecord:     q.EventProcessRecord.clone(db),
		Merchant:               q.Merchant.clone(db),
		NotifyRecord:           q.NotifyRecord.clone(db),
		PaymentAccount:         q.PaymentAccount.clone(db),
		PaymentExpireRecord:    q.PaymentExpireRecord.clone(db),
		PaymentMethod:          q.PaymentMethod.clone(db),
		PaymentOrder:           q.PaymentOrder.clone(db),
		PaymentOrderProduct:    q.PaymentOrderProduct.clone(db),
		PaymentRequestLog:      q.PaymentRequestLog.clone(db),
		RefundOrder:            q.RefundOrder.clone(db),
		RefundOrderProduct:     q.RefundOrderProduct.clone(db),
		RouterAccountStatistic: q.RouterAccountStatistic.clone(db),
		Statistic:              q.Statistic.clone(db),
		TradeStatistic:         q.TradeStatistic.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		Application:            q.Application.replaceDB(db),
		EventProcessRecord:     q.EventProcessRecord.replaceDB(db),
		Merchant:               q.Merchant.replaceDB(db),
		NotifyRecord:           q.NotifyRecord.replaceDB(db),
		PaymentAccount:         q.PaymentAccount.replaceDB(db),
		PaymentExpireRecord:    q.PaymentExpireRecord.replaceDB(db),
		PaymentMethod:          q.PaymentMethod.replaceDB(db),
		PaymentOrder:           q.PaymentOrder.replaceDB(db),
		PaymentOrderProduct:    q.PaymentOrderProduct.replaceDB(db),
		PaymentRequestLog:      q.PaymentRequestLog.replaceDB(db),
		RefundOrder:            q.RefundOrder.replaceDB(db),
		RefundOrderProduct:     q.RefundOrderProduct.replaceDB(db),
		RouterAccountStatistic: q.RouterAccountStatistic.replaceDB(db),
		Statistic:              q.Statistic.replaceDB(db),
		TradeStatistic:         q.TradeStatistic.replaceDB(db),
	}
}

type queryCtx struct {
	Application            IApplicationDo
	EventProcessRecord     IEventProcessRecordDo
	Merchant               IMerchantDo
	NotifyRecord           INotifyRecordDo
	PaymentAccount         IPaymentAccountDo
	PaymentExpireRecord    IPaymentExpireRecordDo
	PaymentMethod          IPaymentMethodDo
	PaymentOrder           IPaymentOrderDo
	PaymentOrderProduct    IPaymentOrderProductDo
	PaymentRequestLog      IPaymentRequestLogDo
	RefundOrder            IRefundOrderDo
	RefundOrderProduct     IRefundOrderProductDo
	RouterAccountStatistic IRouterAccountStatisticDo
	Statistic              IStatisticDo
	TradeStatistic         ITradeStatisticDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Application:            q.Application.WithContext(ctx),
		EventProcessRecord:     q.EventProcessRecord.WithContext(ctx),
		Merchant:               q.Merchant.WithContext(ctx),
		NotifyRecord:           q.NotifyRecord.WithContext(ctx),
		PaymentAccount:         q.PaymentAccount.WithContext(ctx),
		PaymentExpireRecord:    q.PaymentExpireRecord.WithContext(ctx),
		PaymentMethod:          q.PaymentMethod.WithContext(ctx),
		PaymentOrder:           q.PaymentOrder.WithContext(ctx),
		PaymentOrderProduct:    q.PaymentOrderProduct.WithContext(ctx),
		PaymentRequestLog:      q.PaymentRequestLog.WithContext(ctx),
		RefundOrder:            q.RefundOrder.WithContext(ctx),
		RefundOrderProduct:     q.RefundOrderProduct.WithContext(ctx),
		RouterAccountStatistic: q.RouterAccountStatistic.WithContext(ctx),
		Statistic:              q.Statistic.WithContext(ctx),
		TradeStatistic:         q.TradeStatistic.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
