// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newNotifyRecord(db *gorm.DB, opts ...gen.DOOption) notifyRecord {
	_notifyRecord := notifyRecord{}

	_notifyRecord.notifyRecordDo.UseDB(db, opts...)
	_notifyRecord.notifyRecordDo.UseModel(&model.NotifyRecord{})

	tableName := _notifyRecord.notifyRecordDo.TableName()
	_notifyRecord.ALL = field.NewAsterisk(tableName)
	_notifyRecord.ID = field.NewInt64(tableName, "id")
	_notifyRecord.NotifyType = field.NewInt64(tableName, "notify_type")
	_notifyRecord.AppNo = field.NewString(tableName, "app_no")
	_notifyRecord.MchNo = field.NewString(tableName, "mch_no")
	_notifyRecord.Resaon = field.NewString(tableName, "resaon")
	_notifyRecord.OutNo = field.NewString(tableName, "out_no")
	_notifyRecord.TradeNo = field.NewString(tableName, "trade_no")
	_notifyRecord.NotifyURL = field.NewString(tableName, "notify_url")
	_notifyRecord.ResResult = field.NewString(tableName, "res_result")
	_notifyRecord.NotifyCount = field.NewInt64(tableName, "notify_count")
	_notifyRecord.NotifyStatus = field.NewInt64(tableName, "notify_status")
	_notifyRecord.LastNotifyTime = field.NewTime(tableName, "last_notify_time")
	_notifyRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_notifyRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_notifyRecord.fillFieldMap()

	return _notifyRecord
}

// notifyRecord 商户通知记录表,定时任务定期删除7天之前的数据
type notifyRecord struct {
	notifyRecordDo notifyRecordDo

	ALL            field.Asterisk
	ID             field.Int64  // 商户通知记录ID
	NotifyType     field.Int64  // 类型:1-支付,2-退款，3转账
	AppNo          field.String // 应用编号
	MchNo          field.String // 公司编号
	Resaon         field.String // 描述
	OutNo          field.String // 订单号或者退款号
	TradeNo        field.String // 支付系统交易号
	NotifyURL      field.String // 通知地址
	ResResult      field.String // 通知响应结果
	NotifyCount    field.Int64  // 通知次数
	NotifyStatus   field.Int64  // 1待通知， 2已通知 3 通知失败
	LastNotifyTime field.Time   // 最后一次通知时间
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (n notifyRecord) Table(newTableName string) *notifyRecord {
	n.notifyRecordDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notifyRecord) As(alias string) *notifyRecord {
	n.notifyRecordDo.DO = *(n.notifyRecordDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notifyRecord) updateTableName(table string) *notifyRecord {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NotifyType = field.NewInt64(table, "notify_type")
	n.AppNo = field.NewString(table, "app_no")
	n.MchNo = field.NewString(table, "mch_no")
	n.Resaon = field.NewString(table, "resaon")
	n.OutNo = field.NewString(table, "out_no")
	n.TradeNo = field.NewString(table, "trade_no")
	n.NotifyURL = field.NewString(table, "notify_url")
	n.ResResult = field.NewString(table, "res_result")
	n.NotifyCount = field.NewInt64(table, "notify_count")
	n.NotifyStatus = field.NewInt64(table, "notify_status")
	n.LastNotifyTime = field.NewTime(table, "last_notify_time")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *notifyRecord) WithContext(ctx context.Context) INotifyRecordDo {
	return n.notifyRecordDo.WithContext(ctx)
}

func (n notifyRecord) TableName() string { return n.notifyRecordDo.TableName() }

func (n notifyRecord) Alias() string { return n.notifyRecordDo.Alias() }

func (n notifyRecord) Columns(cols ...field.Expr) gen.Columns {
	return n.notifyRecordDo.Columns(cols...)
}

func (n *notifyRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notifyRecord) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 14)
	n.fieldMap["id"] = n.ID
	n.fieldMap["notify_type"] = n.NotifyType
	n.fieldMap["app_no"] = n.AppNo
	n.fieldMap["mch_no"] = n.MchNo
	n.fieldMap["resaon"] = n.Resaon
	n.fieldMap["out_no"] = n.OutNo
	n.fieldMap["trade_no"] = n.TradeNo
	n.fieldMap["notify_url"] = n.NotifyURL
	n.fieldMap["res_result"] = n.ResResult
	n.fieldMap["notify_count"] = n.NotifyCount
	n.fieldMap["notify_status"] = n.NotifyStatus
	n.fieldMap["last_notify_time"] = n.LastNotifyTime
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n notifyRecord) clone(db *gorm.DB) notifyRecord {
	n.notifyRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notifyRecord) replaceDB(db *gorm.DB) notifyRecord {
	n.notifyRecordDo.ReplaceDB(db)
	return n
}

type notifyRecordDo struct{ gen.DO }

type INotifyRecordDo interface {
	gen.SubQuery
	Debug() INotifyRecordDo
	WithContext(ctx context.Context) INotifyRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotifyRecordDo
	WriteDB() INotifyRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotifyRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotifyRecordDo
	Not(conds ...gen.Condition) INotifyRecordDo
	Or(conds ...gen.Condition) INotifyRecordDo
	Select(conds ...field.Expr) INotifyRecordDo
	Where(conds ...gen.Condition) INotifyRecordDo
	Order(conds ...field.Expr) INotifyRecordDo
	Distinct(cols ...field.Expr) INotifyRecordDo
	Omit(cols ...field.Expr) INotifyRecordDo
	Join(table schema.Tabler, on ...field.Expr) INotifyRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotifyRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotifyRecordDo
	Group(cols ...field.Expr) INotifyRecordDo
	Having(conds ...gen.Condition) INotifyRecordDo
	Limit(limit int) INotifyRecordDo
	Offset(offset int) INotifyRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyRecordDo
	Unscoped() INotifyRecordDo
	Create(values ...*model.NotifyRecord) error
	CreateInBatches(values []*model.NotifyRecord, batchSize int) error
	Save(values ...*model.NotifyRecord) error
	First() (*model.NotifyRecord, error)
	Take() (*model.NotifyRecord, error)
	Last() (*model.NotifyRecord, error)
	Find() ([]*model.NotifyRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotifyRecord, err error)
	FindInBatches(result *[]*model.NotifyRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotifyRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotifyRecordDo
	Assign(attrs ...field.AssignExpr) INotifyRecordDo
	Joins(fields ...field.RelationField) INotifyRecordDo
	Preload(fields ...field.RelationField) INotifyRecordDo
	FirstOrInit() (*model.NotifyRecord, error)
	FirstOrCreate() (*model.NotifyRecord, error)
	FindByPage(offset int, limit int) (result []*model.NotifyRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotifyRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notifyRecordDo) Debug() INotifyRecordDo {
	return n.withDO(n.DO.Debug())
}

func (n notifyRecordDo) WithContext(ctx context.Context) INotifyRecordDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notifyRecordDo) ReadDB() INotifyRecordDo {
	return n.Clauses(dbresolver.Read)
}

func (n notifyRecordDo) WriteDB() INotifyRecordDo {
	return n.Clauses(dbresolver.Write)
}

func (n notifyRecordDo) Session(config *gorm.Session) INotifyRecordDo {
	return n.withDO(n.DO.Session(config))
}

func (n notifyRecordDo) Clauses(conds ...clause.Expression) INotifyRecordDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notifyRecordDo) Returning(value interface{}, columns ...string) INotifyRecordDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notifyRecordDo) Not(conds ...gen.Condition) INotifyRecordDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notifyRecordDo) Or(conds ...gen.Condition) INotifyRecordDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notifyRecordDo) Select(conds ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notifyRecordDo) Where(conds ...gen.Condition) INotifyRecordDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notifyRecordDo) Order(conds ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notifyRecordDo) Distinct(cols ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notifyRecordDo) Omit(cols ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notifyRecordDo) Join(table schema.Tabler, on ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notifyRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notifyRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notifyRecordDo) Group(cols ...field.Expr) INotifyRecordDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notifyRecordDo) Having(conds ...gen.Condition) INotifyRecordDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notifyRecordDo) Limit(limit int) INotifyRecordDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notifyRecordDo) Offset(offset int) INotifyRecordDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notifyRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyRecordDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notifyRecordDo) Unscoped() INotifyRecordDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notifyRecordDo) Create(values ...*model.NotifyRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notifyRecordDo) CreateInBatches(values []*model.NotifyRecord, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notifyRecordDo) Save(values ...*model.NotifyRecord) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notifyRecordDo) First() (*model.NotifyRecord, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyRecord), nil
	}
}

func (n notifyRecordDo) Take() (*model.NotifyRecord, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyRecord), nil
	}
}

func (n notifyRecordDo) Last() (*model.NotifyRecord, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyRecord), nil
	}
}

func (n notifyRecordDo) Find() ([]*model.NotifyRecord, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotifyRecord), err
}

func (n notifyRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotifyRecord, err error) {
	buf := make([]*model.NotifyRecord, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notifyRecordDo) FindInBatches(result *[]*model.NotifyRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notifyRecordDo) Attrs(attrs ...field.AssignExpr) INotifyRecordDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notifyRecordDo) Assign(attrs ...field.AssignExpr) INotifyRecordDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notifyRecordDo) Joins(fields ...field.RelationField) INotifyRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notifyRecordDo) Preload(fields ...field.RelationField) INotifyRecordDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notifyRecordDo) FirstOrInit() (*model.NotifyRecord, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyRecord), nil
	}
}

func (n notifyRecordDo) FirstOrCreate() (*model.NotifyRecord, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyRecord), nil
	}
}

func (n notifyRecordDo) FindByPage(offset int, limit int) (result []*model.NotifyRecord, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notifyRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notifyRecordDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notifyRecordDo) Delete(models ...*model.NotifyRecord) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notifyRecordDo) withDO(do gen.Dao) *notifyRecordDo {
	n.DO = *do.(*gen.DO)
	return n
}
