// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentOrderProduct(db *gorm.DB, opts ...gen.DOOption) paymentOrderProduct {
	_paymentOrderProduct := paymentOrderProduct{}

	_paymentOrderProduct.paymentOrderProductDo.UseDB(db, opts...)
	_paymentOrderProduct.paymentOrderProductDo.UseModel(&model.PaymentOrderProduct{})

	tableName := _paymentOrderProduct.paymentOrderProductDo.TableName()
	_paymentOrderProduct.ALL = field.NewAsterisk(tableName)
	_paymentOrderProduct.ID = field.NewInt64(tableName, "id")
	_paymentOrderProduct.ProductName = field.NewString(tableName, "product_name")
	_paymentOrderProduct.AppNo = field.NewString(tableName, "app_no")
	_paymentOrderProduct.MchNo = field.NewString(tableName, "mch_no")
	_paymentOrderProduct.Quantity = field.NewInt64(tableName, "quantity")
	_paymentOrderProduct.Price = field.NewInt64(tableName, "price")
	_paymentOrderProduct.Sku = field.NewString(tableName, "sku")
	_paymentOrderProduct.ProductDesc = field.NewString(tableName, "product_desc")
	_paymentOrderProduct.URL = field.NewString(tableName, "url")
	_paymentOrderProduct.OrderNo = field.NewString(tableName, "order_no")
	_paymentOrderProduct.TradeNo = field.NewString(tableName, "trade_no")
	_paymentOrderProduct.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentOrderProduct.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentOrderProduct.fillFieldMap()

	return _paymentOrderProduct
}

// paymentOrderProduct 支付产品表
type paymentOrderProduct struct {
	paymentOrderProductDo paymentOrderProductDo

	ALL         field.Asterisk
	ID          field.Int64
	ProductName field.String // 订单标题
	AppNo       field.String // 应用编号
	MchNo       field.String // 商户编号
	Quantity    field.Int64  // 购买数量
	Price       field.Int64  // 单价
	Sku         field.String // 商品sku
	ProductDesc field.String // 商品描述
	URL         field.String // 商品链接
	OrderNo     field.String // 订单号
	TradeNo     field.String // 支付单号
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (p paymentOrderProduct) Table(newTableName string) *paymentOrderProduct {
	p.paymentOrderProductDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentOrderProduct) As(alias string) *paymentOrderProduct {
	p.paymentOrderProductDo.DO = *(p.paymentOrderProductDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentOrderProduct) updateTableName(table string) *paymentOrderProduct {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ProductName = field.NewString(table, "product_name")
	p.AppNo = field.NewString(table, "app_no")
	p.MchNo = field.NewString(table, "mch_no")
	p.Quantity = field.NewInt64(table, "quantity")
	p.Price = field.NewInt64(table, "price")
	p.Sku = field.NewString(table, "sku")
	p.ProductDesc = field.NewString(table, "product_desc")
	p.URL = field.NewString(table, "url")
	p.OrderNo = field.NewString(table, "order_no")
	p.TradeNo = field.NewString(table, "trade_no")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentOrderProduct) WithContext(ctx context.Context) IPaymentOrderProductDo {
	return p.paymentOrderProductDo.WithContext(ctx)
}

func (p paymentOrderProduct) TableName() string { return p.paymentOrderProductDo.TableName() }

func (p paymentOrderProduct) Alias() string { return p.paymentOrderProductDo.Alias() }

func (p paymentOrderProduct) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentOrderProductDo.Columns(cols...)
}

func (p *paymentOrderProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentOrderProduct) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["product_name"] = p.ProductName
	p.fieldMap["app_no"] = p.AppNo
	p.fieldMap["mch_no"] = p.MchNo
	p.fieldMap["quantity"] = p.Quantity
	p.fieldMap["price"] = p.Price
	p.fieldMap["sku"] = p.Sku
	p.fieldMap["product_desc"] = p.ProductDesc
	p.fieldMap["url"] = p.URL
	p.fieldMap["order_no"] = p.OrderNo
	p.fieldMap["trade_no"] = p.TradeNo
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentOrderProduct) clone(db *gorm.DB) paymentOrderProduct {
	p.paymentOrderProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentOrderProduct) replaceDB(db *gorm.DB) paymentOrderProduct {
	p.paymentOrderProductDo.ReplaceDB(db)
	return p
}

type paymentOrderProductDo struct{ gen.DO }

type IPaymentOrderProductDo interface {
	gen.SubQuery
	Debug() IPaymentOrderProductDo
	WithContext(ctx context.Context) IPaymentOrderProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentOrderProductDo
	WriteDB() IPaymentOrderProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentOrderProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentOrderProductDo
	Not(conds ...gen.Condition) IPaymentOrderProductDo
	Or(conds ...gen.Condition) IPaymentOrderProductDo
	Select(conds ...field.Expr) IPaymentOrderProductDo
	Where(conds ...gen.Condition) IPaymentOrderProductDo
	Order(conds ...field.Expr) IPaymentOrderProductDo
	Distinct(cols ...field.Expr) IPaymentOrderProductDo
	Omit(cols ...field.Expr) IPaymentOrderProductDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo
	Group(cols ...field.Expr) IPaymentOrderProductDo
	Having(conds ...gen.Condition) IPaymentOrderProductDo
	Limit(limit int) IPaymentOrderProductDo
	Offset(offset int) IPaymentOrderProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentOrderProductDo
	Unscoped() IPaymentOrderProductDo
	Create(values ...*model.PaymentOrderProduct) error
	CreateInBatches(values []*model.PaymentOrderProduct, batchSize int) error
	Save(values ...*model.PaymentOrderProduct) error
	First() (*model.PaymentOrderProduct, error)
	Take() (*model.PaymentOrderProduct, error)
	Last() (*model.PaymentOrderProduct, error)
	Find() ([]*model.PaymentOrderProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentOrderProduct, err error)
	FindInBatches(result *[]*model.PaymentOrderProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentOrderProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentOrderProductDo
	Assign(attrs ...field.AssignExpr) IPaymentOrderProductDo
	Joins(fields ...field.RelationField) IPaymentOrderProductDo
	Preload(fields ...field.RelationField) IPaymentOrderProductDo
	FirstOrInit() (*model.PaymentOrderProduct, error)
	FirstOrCreate() (*model.PaymentOrderProduct, error)
	FindByPage(offset int, limit int) (result []*model.PaymentOrderProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentOrderProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentOrderProductDo) Debug() IPaymentOrderProductDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentOrderProductDo) WithContext(ctx context.Context) IPaymentOrderProductDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentOrderProductDo) ReadDB() IPaymentOrderProductDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentOrderProductDo) WriteDB() IPaymentOrderProductDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentOrderProductDo) Session(config *gorm.Session) IPaymentOrderProductDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentOrderProductDo) Clauses(conds ...clause.Expression) IPaymentOrderProductDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentOrderProductDo) Returning(value interface{}, columns ...string) IPaymentOrderProductDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentOrderProductDo) Not(conds ...gen.Condition) IPaymentOrderProductDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentOrderProductDo) Or(conds ...gen.Condition) IPaymentOrderProductDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentOrderProductDo) Select(conds ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentOrderProductDo) Where(conds ...gen.Condition) IPaymentOrderProductDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentOrderProductDo) Order(conds ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentOrderProductDo) Distinct(cols ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentOrderProductDo) Omit(cols ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentOrderProductDo) Join(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentOrderProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentOrderProductDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentOrderProductDo) Group(cols ...field.Expr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentOrderProductDo) Having(conds ...gen.Condition) IPaymentOrderProductDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentOrderProductDo) Limit(limit int) IPaymentOrderProductDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentOrderProductDo) Offset(offset int) IPaymentOrderProductDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentOrderProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentOrderProductDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentOrderProductDo) Unscoped() IPaymentOrderProductDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentOrderProductDo) Create(values ...*model.PaymentOrderProduct) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentOrderProductDo) CreateInBatches(values []*model.PaymentOrderProduct, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentOrderProductDo) Save(values ...*model.PaymentOrderProduct) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentOrderProductDo) First() (*model.PaymentOrderProduct, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrderProduct), nil
	}
}

func (p paymentOrderProductDo) Take() (*model.PaymentOrderProduct, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrderProduct), nil
	}
}

func (p paymentOrderProductDo) Last() (*model.PaymentOrderProduct, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrderProduct), nil
	}
}

func (p paymentOrderProductDo) Find() ([]*model.PaymentOrderProduct, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentOrderProduct), err
}

func (p paymentOrderProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentOrderProduct, err error) {
	buf := make([]*model.PaymentOrderProduct, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentOrderProductDo) FindInBatches(result *[]*model.PaymentOrderProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentOrderProductDo) Attrs(attrs ...field.AssignExpr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentOrderProductDo) Assign(attrs ...field.AssignExpr) IPaymentOrderProductDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentOrderProductDo) Joins(fields ...field.RelationField) IPaymentOrderProductDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentOrderProductDo) Preload(fields ...field.RelationField) IPaymentOrderProductDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentOrderProductDo) FirstOrInit() (*model.PaymentOrderProduct, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrderProduct), nil
	}
}

func (p paymentOrderProductDo) FirstOrCreate() (*model.PaymentOrderProduct, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrderProduct), nil
	}
}

func (p paymentOrderProductDo) FindByPage(offset int, limit int) (result []*model.PaymentOrderProduct, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentOrderProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentOrderProductDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentOrderProductDo) Delete(models ...*model.PaymentOrderProduct) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentOrderProductDo) withDO(do gen.Dao) *paymentOrderProductDo {
	p.DO = *do.(*gen.DO)
	return p
}
