// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentOrder(db *gorm.DB, opts ...gen.DOOption) paymentOrder {
	_paymentOrder := paymentOrder{}

	_paymentOrder.paymentOrderDo.UseDB(db, opts...)
	_paymentOrder.paymentOrderDo.UseModel(&model.PaymentOrder{})

	tableName := _paymentOrder.paymentOrderDo.TableName()
	_paymentOrder.ALL = field.NewAsterisk(tableName)
	_paymentOrder.ID = field.NewInt64(tableName, "id")
	_paymentOrder.PaymentAccountNo = field.NewString(tableName, "payment_account_no")
	_paymentOrder.AppNo = field.NewString(tableName, "app_no")
	_paymentOrder.MchNo = field.NewString(tableName, "mch_no")
	_paymentOrder.OrderSubject = field.NewString(tableName, "order_subject")
	_paymentOrder.PaymentMethod = field.NewString(tableName, "payment_method")
	_paymentOrder.PaymentProduct = field.NewString(tableName, "payment_product")
	_paymentOrder.OrderNo = field.NewString(tableName, "order_no")
	_paymentOrder.OutMchTradeNo = field.NewString(tableName, "out_mch_trade_no")
	_paymentOrder.TradeNo = field.NewString(tableName, "trade_no")
	_paymentOrder.Device = field.NewString(tableName, "device")
	_paymentOrder.System = field.NewString(tableName, "system")
	_paymentOrder.OrderAmount = field.NewInt64(tableName, "order_amount")
	_paymentOrder.PaymentAmount = field.NewInt64(tableName, "payment_amount")
	_paymentOrder.UserPaymentAmount = field.NewInt64(tableName, "user_payment_amount")
	_paymentOrder.Currency = field.NewString(tableName, "currency")
	_paymentOrder.Status = field.NewInt64(tableName, "status")
	_paymentOrder.StatusFrom = field.NewString(tableName, "status_from")
	_paymentOrder.TimeExpire = field.NewInt64(tableName, "time_expire")
	_paymentOrder.OrderCreate = field.NewInt64(tableName, "order_create")
	_paymentOrder.ExtParam = field.NewString(tableName, "ext_param")
	_paymentOrder.RedirectURL = field.NewString(tableName, "redirect_url")
	_paymentOrder.NotifyURL = field.NewString(tableName, "notify_url")
	_paymentOrder.OrderDesc = field.NewString(tableName, "order_desc")
	_paymentOrder.ThirdCode = field.NewString(tableName, "third_code")
	_paymentOrder.ThirdMsg = field.NewString(tableName, "third_msg")
	_paymentOrder.UserOpenid = field.NewString(tableName, "user_openid")
	_paymentOrder.NotifyStatus = field.NewInt64(tableName, "notify_status")
	_paymentOrder.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentOrder.UpdatedAt = field.NewTime(tableName, "updated_at")
	_paymentOrder.Retry = field.NewInt64(tableName, "retry")

	_paymentOrder.fillFieldMap()

	return _paymentOrder
}

// paymentOrder 支付订单主表
type paymentOrder struct {
	paymentOrderDo paymentOrderDo

	ALL               field.Asterisk
	ID                field.Int64  // 主键ID
	PaymentAccountNo  field.String // payment_account_no
	AppNo             field.String // 应用编号
	MchNo             field.String // 商户编号
	OrderSubject      field.String // 订单标题
	PaymentMethod     field.String // 支付方式：Wechat 微信 | Alipay 支付宝 | 云闪付
	PaymentProduct    field.String // 支付产品：H5 | JSAPI | LITE | APP | Qrcode | Card
	OrderNo           field.String // 订单号
	OutMchTradeNo     field.String // 渠道订单号：微信|支付宝
	TradeNo           field.String // 支付系统交易号
	Device            field.String // 设备
	System            field.String // 操作系统
	OrderAmount       field.Int64  // 订单金额分单位
	PaymentAmount     field.Int64  // 订单实付金额分单位
	UserPaymentAmount field.Int64  // 用户实付金额分单位
	Currency          field.String // 币种
	Status            field.Int64  // 支付状态
	StatusFrom        field.String // 状态修改来源API|WEBHOOK||ADMIN
	TimeExpire        field.Int64  // 支付过期时间
	OrderCreate       field.Int64  // 订单创建时间，时间戳
	ExtParam          field.String // 支付扩展参数
	RedirectURL       field.String // 支付完成跳转url
	NotifyURL         field.String // 异步通知url
	OrderDesc         field.String // 订单描述
	ThirdCode         field.String // 三方接口原返回码code
	ThirdMsg          field.String // 三方接口返回描述
	UserOpenid        field.String // 三方用户标识
	NotifyStatus      field.Int64  // 1 已经回调
	CreatedAt         field.Time   // 创建时间
	UpdatedAt         field.Time   // 更新时间
	Retry             field.Int64  // 重试次数

	fieldMap map[string]field.Expr
}

func (p paymentOrder) Table(newTableName string) *paymentOrder {
	p.paymentOrderDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentOrder) As(alias string) *paymentOrder {
	p.paymentOrderDo.DO = *(p.paymentOrderDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentOrder) updateTableName(table string) *paymentOrder {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PaymentAccountNo = field.NewString(table, "payment_account_no")
	p.AppNo = field.NewString(table, "app_no")
	p.MchNo = field.NewString(table, "mch_no")
	p.OrderSubject = field.NewString(table, "order_subject")
	p.PaymentMethod = field.NewString(table, "payment_method")
	p.PaymentProduct = field.NewString(table, "payment_product")
	p.OrderNo = field.NewString(table, "order_no")
	p.OutMchTradeNo = field.NewString(table, "out_mch_trade_no")
	p.TradeNo = field.NewString(table, "trade_no")
	p.Device = field.NewString(table, "device")
	p.System = field.NewString(table, "system")
	p.OrderAmount = field.NewInt64(table, "order_amount")
	p.PaymentAmount = field.NewInt64(table, "payment_amount")
	p.UserPaymentAmount = field.NewInt64(table, "user_payment_amount")
	p.Currency = field.NewString(table, "currency")
	p.Status = field.NewInt64(table, "status")
	p.StatusFrom = field.NewString(table, "status_from")
	p.TimeExpire = field.NewInt64(table, "time_expire")
	p.OrderCreate = field.NewInt64(table, "order_create")
	p.ExtParam = field.NewString(table, "ext_param")
	p.RedirectURL = field.NewString(table, "redirect_url")
	p.NotifyURL = field.NewString(table, "notify_url")
	p.OrderDesc = field.NewString(table, "order_desc")
	p.ThirdCode = field.NewString(table, "third_code")
	p.ThirdMsg = field.NewString(table, "third_msg")
	p.UserOpenid = field.NewString(table, "user_openid")
	p.NotifyStatus = field.NewInt64(table, "notify_status")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.Retry = field.NewInt64(table, "retry")

	p.fillFieldMap()

	return p
}

func (p *paymentOrder) WithContext(ctx context.Context) IPaymentOrderDo {
	return p.paymentOrderDo.WithContext(ctx)
}

func (p paymentOrder) TableName() string { return p.paymentOrderDo.TableName() }

func (p paymentOrder) Alias() string { return p.paymentOrderDo.Alias() }

func (p paymentOrder) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentOrderDo.Columns(cols...)
}

func (p *paymentOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentOrder) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 31)
	p.fieldMap["id"] = p.ID
	p.fieldMap["payment_account_no"] = p.PaymentAccountNo
	p.fieldMap["app_no"] = p.AppNo
	p.fieldMap["mch_no"] = p.MchNo
	p.fieldMap["order_subject"] = p.OrderSubject
	p.fieldMap["payment_method"] = p.PaymentMethod
	p.fieldMap["payment_product"] = p.PaymentProduct
	p.fieldMap["order_no"] = p.OrderNo
	p.fieldMap["out_mch_trade_no"] = p.OutMchTradeNo
	p.fieldMap["trade_no"] = p.TradeNo
	p.fieldMap["device"] = p.Device
	p.fieldMap["system"] = p.System
	p.fieldMap["order_amount"] = p.OrderAmount
	p.fieldMap["payment_amount"] = p.PaymentAmount
	p.fieldMap["user_payment_amount"] = p.UserPaymentAmount
	p.fieldMap["currency"] = p.Currency
	p.fieldMap["status"] = p.Status
	p.fieldMap["status_from"] = p.StatusFrom
	p.fieldMap["time_expire"] = p.TimeExpire
	p.fieldMap["order_create"] = p.OrderCreate
	p.fieldMap["ext_param"] = p.ExtParam
	p.fieldMap["redirect_url"] = p.RedirectURL
	p.fieldMap["notify_url"] = p.NotifyURL
	p.fieldMap["order_desc"] = p.OrderDesc
	p.fieldMap["third_code"] = p.ThirdCode
	p.fieldMap["third_msg"] = p.ThirdMsg
	p.fieldMap["user_openid"] = p.UserOpenid
	p.fieldMap["notify_status"] = p.NotifyStatus
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["retry"] = p.Retry
}

func (p paymentOrder) clone(db *gorm.DB) paymentOrder {
	p.paymentOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentOrder) replaceDB(db *gorm.DB) paymentOrder {
	p.paymentOrderDo.ReplaceDB(db)
	return p
}

type paymentOrderDo struct{ gen.DO }

type IPaymentOrderDo interface {
	gen.SubQuery
	Debug() IPaymentOrderDo
	WithContext(ctx context.Context) IPaymentOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentOrderDo
	WriteDB() IPaymentOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentOrderDo
	Not(conds ...gen.Condition) IPaymentOrderDo
	Or(conds ...gen.Condition) IPaymentOrderDo
	Select(conds ...field.Expr) IPaymentOrderDo
	Where(conds ...gen.Condition) IPaymentOrderDo
	Order(conds ...field.Expr) IPaymentOrderDo
	Distinct(cols ...field.Expr) IPaymentOrderDo
	Omit(cols ...field.Expr) IPaymentOrderDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderDo
	Group(cols ...field.Expr) IPaymentOrderDo
	Having(conds ...gen.Condition) IPaymentOrderDo
	Limit(limit int) IPaymentOrderDo
	Offset(offset int) IPaymentOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentOrderDo
	Unscoped() IPaymentOrderDo
	Create(values ...*model.PaymentOrder) error
	CreateInBatches(values []*model.PaymentOrder, batchSize int) error
	Save(values ...*model.PaymentOrder) error
	First() (*model.PaymentOrder, error)
	Take() (*model.PaymentOrder, error)
	Last() (*model.PaymentOrder, error)
	Find() ([]*model.PaymentOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentOrder, err error)
	FindInBatches(result *[]*model.PaymentOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentOrderDo
	Assign(attrs ...field.AssignExpr) IPaymentOrderDo
	Joins(fields ...field.RelationField) IPaymentOrderDo
	Preload(fields ...field.RelationField) IPaymentOrderDo
	FirstOrInit() (*model.PaymentOrder, error)
	FirstOrCreate() (*model.PaymentOrder, error)
	FindByPage(offset int, limit int) (result []*model.PaymentOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentOrderDo) Debug() IPaymentOrderDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentOrderDo) WithContext(ctx context.Context) IPaymentOrderDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentOrderDo) ReadDB() IPaymentOrderDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentOrderDo) WriteDB() IPaymentOrderDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentOrderDo) Session(config *gorm.Session) IPaymentOrderDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentOrderDo) Clauses(conds ...clause.Expression) IPaymentOrderDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentOrderDo) Returning(value interface{}, columns ...string) IPaymentOrderDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentOrderDo) Not(conds ...gen.Condition) IPaymentOrderDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentOrderDo) Or(conds ...gen.Condition) IPaymentOrderDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentOrderDo) Select(conds ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentOrderDo) Where(conds ...gen.Condition) IPaymentOrderDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentOrderDo) Order(conds ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentOrderDo) Distinct(cols ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentOrderDo) Omit(cols ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentOrderDo) Join(table schema.Tabler, on ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentOrderDo) Group(cols ...field.Expr) IPaymentOrderDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentOrderDo) Having(conds ...gen.Condition) IPaymentOrderDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentOrderDo) Limit(limit int) IPaymentOrderDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentOrderDo) Offset(offset int) IPaymentOrderDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentOrderDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentOrderDo) Unscoped() IPaymentOrderDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentOrderDo) Create(values ...*model.PaymentOrder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentOrderDo) CreateInBatches(values []*model.PaymentOrder, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentOrderDo) Save(values ...*model.PaymentOrder) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentOrderDo) First() (*model.PaymentOrder, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrder), nil
	}
}

func (p paymentOrderDo) Take() (*model.PaymentOrder, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrder), nil
	}
}

func (p paymentOrderDo) Last() (*model.PaymentOrder, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrder), nil
	}
}

func (p paymentOrderDo) Find() ([]*model.PaymentOrder, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentOrder), err
}

func (p paymentOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentOrder, err error) {
	buf := make([]*model.PaymentOrder, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentOrderDo) FindInBatches(result *[]*model.PaymentOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentOrderDo) Attrs(attrs ...field.AssignExpr) IPaymentOrderDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentOrderDo) Assign(attrs ...field.AssignExpr) IPaymentOrderDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentOrderDo) Joins(fields ...field.RelationField) IPaymentOrderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentOrderDo) Preload(fields ...field.RelationField) IPaymentOrderDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentOrderDo) FirstOrInit() (*model.PaymentOrder, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrder), nil
	}
}

func (p paymentOrderDo) FirstOrCreate() (*model.PaymentOrder, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentOrder), nil
	}
}

func (p paymentOrderDo) FindByPage(offset int, limit int) (result []*model.PaymentOrder, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentOrderDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentOrderDo) Delete(models ...*model.PaymentOrder) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentOrderDo) withDO(do gen.Dao) *paymentOrderDo {
	p.DO = *do.(*gen.DO)
	return p
}
