// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentAccount(db *gorm.DB, opts ...gen.DOOption) paymentAccount {
	_paymentAccount := paymentAccount{}

	_paymentAccount.paymentAccountDo.UseDB(db, opts...)
	_paymentAccount.paymentAccountDo.UseModel(&model.PaymentAccount{})

	tableName := _paymentAccount.paymentAccountDo.TableName()
	_paymentAccount.ALL = field.NewAsterisk(tableName)
	_paymentAccount.ID = field.NewInt64(tableName, "id")
	_paymentAccount.Name = field.NewString(tableName, "name")
	_paymentAccount.Remark = field.NewString(tableName, "remark")
	_paymentAccount.AppNo = field.NewString(tableName, "app_no")
	_paymentAccount.MchNo = field.NewString(tableName, "mch_no")
	_paymentAccount.Channel = field.NewString(tableName, "channel")
	_paymentAccount.Status = field.NewInt64(tableName, "status")
	_paymentAccount.Extend = field.NewString(tableName, "extend")
	_paymentAccount.MaxLimit = field.NewInt64(tableName, "max_limit")
	_paymentAccount.ValidateStatus = field.NewInt64(tableName, "validate_status")
	_paymentAccount.AccountNo = field.NewString(tableName, "account_no")
	_paymentAccount.ChannelConfig = field.NewString(tableName, "channel_config")
	_paymentAccount.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentAccount.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentAccount.fillFieldMap()

	return _paymentAccount
}

// paymentAccount 支付主体账号
type paymentAccount struct {
	paymentAccountDo paymentAccountDo

	ALL            field.Asterisk
	ID             field.Int64
	Name           field.String // 名字标识
	Remark         field.String // 描述
	AppNo          field.String // 应用编号
	MchNo          field.String // 商户编号
	Channel        field.String // 支付渠道：Wechat 微信 | Alipay 支付宝 | Lakala 拉卡拉 | Fuiou 富有
	Status         field.Int64  // 2 停用 1 正常
	Extend         field.String // 拓展配置
	MaxLimit       field.Int64  // 单日最大支付次数
	ValidateStatus field.Int64  // 是否验证 0 没有 1 验证通过
	AccountNo      field.String // 账户编号
	ChannelConfig  field.String // 各个渠道的私有配置
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (p paymentAccount) Table(newTableName string) *paymentAccount {
	p.paymentAccountDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentAccount) As(alias string) *paymentAccount {
	p.paymentAccountDo.DO = *(p.paymentAccountDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentAccount) updateTableName(table string) *paymentAccount {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Name = field.NewString(table, "name")
	p.Remark = field.NewString(table, "remark")
	p.AppNo = field.NewString(table, "app_no")
	p.MchNo = field.NewString(table, "mch_no")
	p.Channel = field.NewString(table, "channel")
	p.Status = field.NewInt64(table, "status")
	p.Extend = field.NewString(table, "extend")
	p.MaxLimit = field.NewInt64(table, "max_limit")
	p.ValidateStatus = field.NewInt64(table, "validate_status")
	p.AccountNo = field.NewString(table, "account_no")
	p.ChannelConfig = field.NewString(table, "channel_config")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentAccount) WithContext(ctx context.Context) IPaymentAccountDo {
	return p.paymentAccountDo.WithContext(ctx)
}

func (p paymentAccount) TableName() string { return p.paymentAccountDo.TableName() }

func (p paymentAccount) Alias() string { return p.paymentAccountDo.Alias() }

func (p paymentAccount) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentAccountDo.Columns(cols...)
}

func (p *paymentAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentAccount) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 14)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["app_no"] = p.AppNo
	p.fieldMap["mch_no"] = p.MchNo
	p.fieldMap["channel"] = p.Channel
	p.fieldMap["status"] = p.Status
	p.fieldMap["extend"] = p.Extend
	p.fieldMap["max_limit"] = p.MaxLimit
	p.fieldMap["validate_status"] = p.ValidateStatus
	p.fieldMap["account_no"] = p.AccountNo
	p.fieldMap["channel_config"] = p.ChannelConfig
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentAccount) clone(db *gorm.DB) paymentAccount {
	p.paymentAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentAccount) replaceDB(db *gorm.DB) paymentAccount {
	p.paymentAccountDo.ReplaceDB(db)
	return p
}

type paymentAccountDo struct{ gen.DO }

type IPaymentAccountDo interface {
	gen.SubQuery
	Debug() IPaymentAccountDo
	WithContext(ctx context.Context) IPaymentAccountDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentAccountDo
	WriteDB() IPaymentAccountDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentAccountDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentAccountDo
	Not(conds ...gen.Condition) IPaymentAccountDo
	Or(conds ...gen.Condition) IPaymentAccountDo
	Select(conds ...field.Expr) IPaymentAccountDo
	Where(conds ...gen.Condition) IPaymentAccountDo
	Order(conds ...field.Expr) IPaymentAccountDo
	Distinct(cols ...field.Expr) IPaymentAccountDo
	Omit(cols ...field.Expr) IPaymentAccountDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentAccountDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentAccountDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentAccountDo
	Group(cols ...field.Expr) IPaymentAccountDo
	Having(conds ...gen.Condition) IPaymentAccountDo
	Limit(limit int) IPaymentAccountDo
	Offset(offset int) IPaymentAccountDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentAccountDo
	Unscoped() IPaymentAccountDo
	Create(values ...*model.PaymentAccount) error
	CreateInBatches(values []*model.PaymentAccount, batchSize int) error
	Save(values ...*model.PaymentAccount) error
	First() (*model.PaymentAccount, error)
	Take() (*model.PaymentAccount, error)
	Last() (*model.PaymentAccount, error)
	Find() ([]*model.PaymentAccount, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentAccount, err error)
	FindInBatches(result *[]*model.PaymentAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentAccount) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentAccountDo
	Assign(attrs ...field.AssignExpr) IPaymentAccountDo
	Joins(fields ...field.RelationField) IPaymentAccountDo
	Preload(fields ...field.RelationField) IPaymentAccountDo
	FirstOrInit() (*model.PaymentAccount, error)
	FirstOrCreate() (*model.PaymentAccount, error)
	FindByPage(offset int, limit int) (result []*model.PaymentAccount, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentAccountDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentAccountDo) Debug() IPaymentAccountDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentAccountDo) WithContext(ctx context.Context) IPaymentAccountDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentAccountDo) ReadDB() IPaymentAccountDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentAccountDo) WriteDB() IPaymentAccountDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentAccountDo) Session(config *gorm.Session) IPaymentAccountDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentAccountDo) Clauses(conds ...clause.Expression) IPaymentAccountDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentAccountDo) Returning(value interface{}, columns ...string) IPaymentAccountDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentAccountDo) Not(conds ...gen.Condition) IPaymentAccountDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentAccountDo) Or(conds ...gen.Condition) IPaymentAccountDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentAccountDo) Select(conds ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentAccountDo) Where(conds ...gen.Condition) IPaymentAccountDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentAccountDo) Order(conds ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentAccountDo) Distinct(cols ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentAccountDo) Omit(cols ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentAccountDo) Join(table schema.Tabler, on ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentAccountDo) Group(cols ...field.Expr) IPaymentAccountDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentAccountDo) Having(conds ...gen.Condition) IPaymentAccountDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentAccountDo) Limit(limit int) IPaymentAccountDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentAccountDo) Offset(offset int) IPaymentAccountDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentAccountDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentAccountDo) Unscoped() IPaymentAccountDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentAccountDo) Create(values ...*model.PaymentAccount) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentAccountDo) CreateInBatches(values []*model.PaymentAccount, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentAccountDo) Save(values ...*model.PaymentAccount) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentAccountDo) First() (*model.PaymentAccount, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentAccount), nil
	}
}

func (p paymentAccountDo) Take() (*model.PaymentAccount, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentAccount), nil
	}
}

func (p paymentAccountDo) Last() (*model.PaymentAccount, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentAccount), nil
	}
}

func (p paymentAccountDo) Find() ([]*model.PaymentAccount, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentAccount), err
}

func (p paymentAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentAccount, err error) {
	buf := make([]*model.PaymentAccount, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentAccountDo) FindInBatches(result *[]*model.PaymentAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentAccountDo) Attrs(attrs ...field.AssignExpr) IPaymentAccountDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentAccountDo) Assign(attrs ...field.AssignExpr) IPaymentAccountDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentAccountDo) Joins(fields ...field.RelationField) IPaymentAccountDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentAccountDo) Preload(fields ...field.RelationField) IPaymentAccountDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentAccountDo) FirstOrInit() (*model.PaymentAccount, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentAccount), nil
	}
}

func (p paymentAccountDo) FirstOrCreate() (*model.PaymentAccount, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentAccount), nil
	}
}

func (p paymentAccountDo) FindByPage(offset int, limit int) (result []*model.PaymentAccount, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentAccountDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentAccountDo) Delete(models ...*model.PaymentAccount) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentAccountDo) withDO(do gen.Dao) *paymentAccountDo {
	p.DO = *do.(*gen.DO)
	return p
}
