// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentMethod(db *gorm.DB, opts ...gen.DOOption) paymentMethod {
	_paymentMethod := paymentMethod{}

	_paymentMethod.paymentMethodDo.UseDB(db, opts...)
	_paymentMethod.paymentMethodDo.UseModel(&model.PaymentMethod{})

	tableName := _paymentMethod.paymentMethodDo.TableName()
	_paymentMethod.ALL = field.NewAsterisk(tableName)
	_paymentMethod.ID = field.NewInt64(tableName, "id")
	_paymentMethod.PaymentAccountID = field.NewInt64(tableName, "payment_account_id")
	_paymentMethod.PaymentMethod = field.NewString(tableName, "payment_method")
	_paymentMethod.PaymentProduct = field.NewString(tableName, "payment_product")
	_paymentMethod.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentMethod.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentMethod.fillFieldMap()

	return _paymentMethod
}

// paymentMethod 支付方式
type paymentMethod struct {
	paymentMethodDo paymentMethodDo

	ALL              field.Asterisk
	ID               field.Int64
	PaymentAccountID field.Int64  // payemnt_account_id表自增id
	PaymentMethod    field.String // 支付方式：Wechat 微信 | Alipay 支付宝 | 云闪付
	PaymentProduct   field.String // 支付产品：H5 | JSAPI | LITE | APP | Qrcode | Card
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (p paymentMethod) Table(newTableName string) *paymentMethod {
	p.paymentMethodDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentMethod) As(alias string) *paymentMethod {
	p.paymentMethodDo.DO = *(p.paymentMethodDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentMethod) updateTableName(table string) *paymentMethod {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.PaymentAccountID = field.NewInt64(table, "payment_account_id")
	p.PaymentMethod = field.NewString(table, "payment_method")
	p.PaymentProduct = field.NewString(table, "payment_product")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentMethod) WithContext(ctx context.Context) IPaymentMethodDo {
	return p.paymentMethodDo.WithContext(ctx)
}

func (p paymentMethod) TableName() string { return p.paymentMethodDo.TableName() }

func (p paymentMethod) Alias() string { return p.paymentMethodDo.Alias() }

func (p paymentMethod) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentMethodDo.Columns(cols...)
}

func (p *paymentMethod) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentMethod) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["payment_account_id"] = p.PaymentAccountID
	p.fieldMap["payment_method"] = p.PaymentMethod
	p.fieldMap["payment_product"] = p.PaymentProduct
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentMethod) clone(db *gorm.DB) paymentMethod {
	p.paymentMethodDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentMethod) replaceDB(db *gorm.DB) paymentMethod {
	p.paymentMethodDo.ReplaceDB(db)
	return p
}

type paymentMethodDo struct{ gen.DO }

type IPaymentMethodDo interface {
	gen.SubQuery
	Debug() IPaymentMethodDo
	WithContext(ctx context.Context) IPaymentMethodDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentMethodDo
	WriteDB() IPaymentMethodDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentMethodDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentMethodDo
	Not(conds ...gen.Condition) IPaymentMethodDo
	Or(conds ...gen.Condition) IPaymentMethodDo
	Select(conds ...field.Expr) IPaymentMethodDo
	Where(conds ...gen.Condition) IPaymentMethodDo
	Order(conds ...field.Expr) IPaymentMethodDo
	Distinct(cols ...field.Expr) IPaymentMethodDo
	Omit(cols ...field.Expr) IPaymentMethodDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentMethodDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentMethodDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentMethodDo
	Group(cols ...field.Expr) IPaymentMethodDo
	Having(conds ...gen.Condition) IPaymentMethodDo
	Limit(limit int) IPaymentMethodDo
	Offset(offset int) IPaymentMethodDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentMethodDo
	Unscoped() IPaymentMethodDo
	Create(values ...*model.PaymentMethod) error
	CreateInBatches(values []*model.PaymentMethod, batchSize int) error
	Save(values ...*model.PaymentMethod) error
	First() (*model.PaymentMethod, error)
	Take() (*model.PaymentMethod, error)
	Last() (*model.PaymentMethod, error)
	Find() ([]*model.PaymentMethod, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentMethod, err error)
	FindInBatches(result *[]*model.PaymentMethod, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentMethod) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentMethodDo
	Assign(attrs ...field.AssignExpr) IPaymentMethodDo
	Joins(fields ...field.RelationField) IPaymentMethodDo
	Preload(fields ...field.RelationField) IPaymentMethodDo
	FirstOrInit() (*model.PaymentMethod, error)
	FirstOrCreate() (*model.PaymentMethod, error)
	FindByPage(offset int, limit int) (result []*model.PaymentMethod, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentMethodDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentMethodDo) Debug() IPaymentMethodDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentMethodDo) WithContext(ctx context.Context) IPaymentMethodDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentMethodDo) ReadDB() IPaymentMethodDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentMethodDo) WriteDB() IPaymentMethodDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentMethodDo) Session(config *gorm.Session) IPaymentMethodDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentMethodDo) Clauses(conds ...clause.Expression) IPaymentMethodDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentMethodDo) Returning(value interface{}, columns ...string) IPaymentMethodDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentMethodDo) Not(conds ...gen.Condition) IPaymentMethodDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentMethodDo) Or(conds ...gen.Condition) IPaymentMethodDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentMethodDo) Select(conds ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentMethodDo) Where(conds ...gen.Condition) IPaymentMethodDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentMethodDo) Order(conds ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentMethodDo) Distinct(cols ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentMethodDo) Omit(cols ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentMethodDo) Join(table schema.Tabler, on ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentMethodDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentMethodDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentMethodDo) Group(cols ...field.Expr) IPaymentMethodDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentMethodDo) Having(conds ...gen.Condition) IPaymentMethodDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentMethodDo) Limit(limit int) IPaymentMethodDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentMethodDo) Offset(offset int) IPaymentMethodDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentMethodDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentMethodDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentMethodDo) Unscoped() IPaymentMethodDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentMethodDo) Create(values ...*model.PaymentMethod) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentMethodDo) CreateInBatches(values []*model.PaymentMethod, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentMethodDo) Save(values ...*model.PaymentMethod) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentMethodDo) First() (*model.PaymentMethod, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentMethod), nil
	}
}

func (p paymentMethodDo) Take() (*model.PaymentMethod, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentMethod), nil
	}
}

func (p paymentMethodDo) Last() (*model.PaymentMethod, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentMethod), nil
	}
}

func (p paymentMethodDo) Find() ([]*model.PaymentMethod, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentMethod), err
}

func (p paymentMethodDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentMethod, err error) {
	buf := make([]*model.PaymentMethod, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentMethodDo) FindInBatches(result *[]*model.PaymentMethod, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentMethodDo) Attrs(attrs ...field.AssignExpr) IPaymentMethodDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentMethodDo) Assign(attrs ...field.AssignExpr) IPaymentMethodDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentMethodDo) Joins(fields ...field.RelationField) IPaymentMethodDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentMethodDo) Preload(fields ...field.RelationField) IPaymentMethodDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentMethodDo) FirstOrInit() (*model.PaymentMethod, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentMethod), nil
	}
}

func (p paymentMethodDo) FirstOrCreate() (*model.PaymentMethod, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentMethod), nil
	}
}

func (p paymentMethodDo) FindByPage(offset int, limit int) (result []*model.PaymentMethod, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentMethodDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentMethodDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentMethodDo) Delete(models ...*model.PaymentMethod) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentMethodDo) withDO(do gen.Dao) *paymentMethodDo {
	p.DO = *do.(*gen.DO)
	return p
}
