// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentRequestLog(db *gorm.DB, opts ...gen.DOOption) paymentRequestLog {
	_paymentRequestLog := paymentRequestLog{}

	_paymentRequestLog.paymentRequestLogDo.UseDB(db, opts...)
	_paymentRequestLog.paymentRequestLogDo.UseModel(&model.PaymentRequestLog{})

	tableName := _paymentRequestLog.paymentRequestLogDo.TableName()
	_paymentRequestLog.ALL = field.NewAsterisk(tableName)
	_paymentRequestLog.ID = field.NewInt64(tableName, "id")
	_paymentRequestLog.Request = field.NewString(tableName, "request")
	_paymentRequestLog.Response = field.NewString(tableName, "response")
	_paymentRequestLog.OrderNo = field.NewString(tableName, "order_no")
	_paymentRequestLog.TradeNo = field.NewString(tableName, "trade_no")
	_paymentRequestLog.MchNo = field.NewString(tableName, "mch_no")
	_paymentRequestLog.AppNo = field.NewString(tableName, "app_no")
	_paymentRequestLog.RequestID = field.NewString(tableName, "request_id")
	_paymentRequestLog.CreatedAt = field.NewTime(tableName, "created_at")

	_paymentRequestLog.fillFieldMap()

	return _paymentRequestLog
}

// paymentRequestLog 请求日志
type paymentRequestLog struct {
	paymentRequestLogDo paymentRequestLogDo

	ALL       field.Asterisk
	ID        field.Int64
	Request   field.String // 请求body
	Response  field.String // 返回body
	OrderNo   field.String // 订单号
	TradeNo   field.String // 支付系统交易号
	MchNo     field.String
	AppNo     field.String
	RequestID field.String // 请求ID
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (p paymentRequestLog) Table(newTableName string) *paymentRequestLog {
	p.paymentRequestLogDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentRequestLog) As(alias string) *paymentRequestLog {
	p.paymentRequestLogDo.DO = *(p.paymentRequestLogDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentRequestLog) updateTableName(table string) *paymentRequestLog {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.Request = field.NewString(table, "request")
	p.Response = field.NewString(table, "response")
	p.OrderNo = field.NewString(table, "order_no")
	p.TradeNo = field.NewString(table, "trade_no")
	p.MchNo = field.NewString(table, "mch_no")
	p.AppNo = field.NewString(table, "app_no")
	p.RequestID = field.NewString(table, "request_id")
	p.CreatedAt = field.NewTime(table, "created_at")

	p.fillFieldMap()

	return p
}

func (p *paymentRequestLog) WithContext(ctx context.Context) IPaymentRequestLogDo {
	return p.paymentRequestLogDo.WithContext(ctx)
}

func (p paymentRequestLog) TableName() string { return p.paymentRequestLogDo.TableName() }

func (p paymentRequestLog) Alias() string { return p.paymentRequestLogDo.Alias() }

func (p paymentRequestLog) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentRequestLogDo.Columns(cols...)
}

func (p *paymentRequestLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentRequestLog) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["request"] = p.Request
	p.fieldMap["response"] = p.Response
	p.fieldMap["order_no"] = p.OrderNo
	p.fieldMap["trade_no"] = p.TradeNo
	p.fieldMap["mch_no"] = p.MchNo
	p.fieldMap["app_no"] = p.AppNo
	p.fieldMap["request_id"] = p.RequestID
	p.fieldMap["created_at"] = p.CreatedAt
}

func (p paymentRequestLog) clone(db *gorm.DB) paymentRequestLog {
	p.paymentRequestLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentRequestLog) replaceDB(db *gorm.DB) paymentRequestLog {
	p.paymentRequestLogDo.ReplaceDB(db)
	return p
}

type paymentRequestLogDo struct{ gen.DO }

type IPaymentRequestLogDo interface {
	gen.SubQuery
	Debug() IPaymentRequestLogDo
	WithContext(ctx context.Context) IPaymentRequestLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentRequestLogDo
	WriteDB() IPaymentRequestLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentRequestLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentRequestLogDo
	Not(conds ...gen.Condition) IPaymentRequestLogDo
	Or(conds ...gen.Condition) IPaymentRequestLogDo
	Select(conds ...field.Expr) IPaymentRequestLogDo
	Where(conds ...gen.Condition) IPaymentRequestLogDo
	Order(conds ...field.Expr) IPaymentRequestLogDo
	Distinct(cols ...field.Expr) IPaymentRequestLogDo
	Omit(cols ...field.Expr) IPaymentRequestLogDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo
	Group(cols ...field.Expr) IPaymentRequestLogDo
	Having(conds ...gen.Condition) IPaymentRequestLogDo
	Limit(limit int) IPaymentRequestLogDo
	Offset(offset int) IPaymentRequestLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentRequestLogDo
	Unscoped() IPaymentRequestLogDo
	Create(values ...*model.PaymentRequestLog) error
	CreateInBatches(values []*model.PaymentRequestLog, batchSize int) error
	Save(values ...*model.PaymentRequestLog) error
	First() (*model.PaymentRequestLog, error)
	Take() (*model.PaymentRequestLog, error)
	Last() (*model.PaymentRequestLog, error)
	Find() ([]*model.PaymentRequestLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentRequestLog, err error)
	FindInBatches(result *[]*model.PaymentRequestLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentRequestLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentRequestLogDo
	Assign(attrs ...field.AssignExpr) IPaymentRequestLogDo
	Joins(fields ...field.RelationField) IPaymentRequestLogDo
	Preload(fields ...field.RelationField) IPaymentRequestLogDo
	FirstOrInit() (*model.PaymentRequestLog, error)
	FirstOrCreate() (*model.PaymentRequestLog, error)
	FindByPage(offset int, limit int) (result []*model.PaymentRequestLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentRequestLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentRequestLogDo) Debug() IPaymentRequestLogDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentRequestLogDo) WithContext(ctx context.Context) IPaymentRequestLogDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentRequestLogDo) ReadDB() IPaymentRequestLogDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentRequestLogDo) WriteDB() IPaymentRequestLogDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentRequestLogDo) Session(config *gorm.Session) IPaymentRequestLogDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentRequestLogDo) Clauses(conds ...clause.Expression) IPaymentRequestLogDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentRequestLogDo) Returning(value interface{}, columns ...string) IPaymentRequestLogDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentRequestLogDo) Not(conds ...gen.Condition) IPaymentRequestLogDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentRequestLogDo) Or(conds ...gen.Condition) IPaymentRequestLogDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentRequestLogDo) Select(conds ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentRequestLogDo) Where(conds ...gen.Condition) IPaymentRequestLogDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentRequestLogDo) Order(conds ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentRequestLogDo) Distinct(cols ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentRequestLogDo) Omit(cols ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentRequestLogDo) Join(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentRequestLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentRequestLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentRequestLogDo) Group(cols ...field.Expr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentRequestLogDo) Having(conds ...gen.Condition) IPaymentRequestLogDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentRequestLogDo) Limit(limit int) IPaymentRequestLogDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentRequestLogDo) Offset(offset int) IPaymentRequestLogDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentRequestLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentRequestLogDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentRequestLogDo) Unscoped() IPaymentRequestLogDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentRequestLogDo) Create(values ...*model.PaymentRequestLog) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentRequestLogDo) CreateInBatches(values []*model.PaymentRequestLog, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentRequestLogDo) Save(values ...*model.PaymentRequestLog) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentRequestLogDo) First() (*model.PaymentRequestLog, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRequestLog), nil
	}
}

func (p paymentRequestLogDo) Take() (*model.PaymentRequestLog, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRequestLog), nil
	}
}

func (p paymentRequestLogDo) Last() (*model.PaymentRequestLog, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRequestLog), nil
	}
}

func (p paymentRequestLogDo) Find() ([]*model.PaymentRequestLog, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentRequestLog), err
}

func (p paymentRequestLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentRequestLog, err error) {
	buf := make([]*model.PaymentRequestLog, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentRequestLogDo) FindInBatches(result *[]*model.PaymentRequestLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentRequestLogDo) Attrs(attrs ...field.AssignExpr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentRequestLogDo) Assign(attrs ...field.AssignExpr) IPaymentRequestLogDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentRequestLogDo) Joins(fields ...field.RelationField) IPaymentRequestLogDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentRequestLogDo) Preload(fields ...field.RelationField) IPaymentRequestLogDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentRequestLogDo) FirstOrInit() (*model.PaymentRequestLog, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRequestLog), nil
	}
}

func (p paymentRequestLogDo) FirstOrCreate() (*model.PaymentRequestLog, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRequestLog), nil
	}
}

func (p paymentRequestLogDo) FindByPage(offset int, limit int) (result []*model.PaymentRequestLog, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentRequestLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentRequestLogDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentRequestLogDo) Delete(models ...*model.PaymentRequestLog) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentRequestLogDo) withDO(do gen.Dao) *paymentRequestLogDo {
	p.DO = *do.(*gen.DO)
	return p
}
