// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newPaymentExpireRecord(db *gorm.DB, opts ...gen.DOOption) paymentExpireRecord {
	_paymentExpireRecord := paymentExpireRecord{}

	_paymentExpireRecord.paymentExpireRecordDo.UseDB(db, opts...)
	_paymentExpireRecord.paymentExpireRecordDo.UseModel(&model.PaymentExpireRecord{})

	tableName := _paymentExpireRecord.paymentExpireRecordDo.TableName()
	_paymentExpireRecord.ALL = field.NewAsterisk(tableName)
	_paymentExpireRecord.ID = field.NewInt64(tableName, "id")
	_paymentExpireRecord.AppNo = field.NewString(tableName, "app_no")
	_paymentExpireRecord.MchNo = field.NewString(tableName, "mch_no")
	_paymentExpireRecord.OrderNo = field.NewString(tableName, "order_no")
	_paymentExpireRecord.TradeNo = field.NewString(tableName, "trade_no")
	_paymentExpireRecord.ExpireTime = field.NewTime(tableName, "expire_time")
	_paymentExpireRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentExpireRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentExpireRecord.fillFieldMap()

	return _paymentExpireRecord
}

// paymentExpireRecord 支付过期记录表,定时任务定期删除1天之前的数据
type paymentExpireRecord struct {
	paymentExpireRecordDo paymentExpireRecordDo

	ALL        field.Asterisk
	ID         field.Int64  // ID
	AppNo      field.String // 应用编号
	MchNo      field.String // 公司编号
	OrderNo    field.String // 订单号号
	TradeNo    field.String // 支付系统交易号
	ExpireTime field.Time   // 过期时间
	CreatedAt  field.Time
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (p paymentExpireRecord) Table(newTableName string) *paymentExpireRecord {
	p.paymentExpireRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentExpireRecord) As(alias string) *paymentExpireRecord {
	p.paymentExpireRecordDo.DO = *(p.paymentExpireRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentExpireRecord) updateTableName(table string) *paymentExpireRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.AppNo = field.NewString(table, "app_no")
	p.MchNo = field.NewString(table, "mch_no")
	p.OrderNo = field.NewString(table, "order_no")
	p.TradeNo = field.NewString(table, "trade_no")
	p.ExpireTime = field.NewTime(table, "expire_time")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentExpireRecord) WithContext(ctx context.Context) IPaymentExpireRecordDo {
	return p.paymentExpireRecordDo.WithContext(ctx)
}

func (p paymentExpireRecord) TableName() string { return p.paymentExpireRecordDo.TableName() }

func (p paymentExpireRecord) Alias() string { return p.paymentExpireRecordDo.Alias() }

func (p paymentExpireRecord) Columns(cols ...field.Expr) gen.Columns {
	return p.paymentExpireRecordDo.Columns(cols...)
}

func (p *paymentExpireRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentExpireRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 8)
	p.fieldMap["id"] = p.ID
	p.fieldMap["app_no"] = p.AppNo
	p.fieldMap["mch_no"] = p.MchNo
	p.fieldMap["order_no"] = p.OrderNo
	p.fieldMap["trade_no"] = p.TradeNo
	p.fieldMap["expire_time"] = p.ExpireTime
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentExpireRecord) clone(db *gorm.DB) paymentExpireRecord {
	p.paymentExpireRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentExpireRecord) replaceDB(db *gorm.DB) paymentExpireRecord {
	p.paymentExpireRecordDo.ReplaceDB(db)
	return p
}

type paymentExpireRecordDo struct{ gen.DO }

type IPaymentExpireRecordDo interface {
	gen.SubQuery
	Debug() IPaymentExpireRecordDo
	WithContext(ctx context.Context) IPaymentExpireRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPaymentExpireRecordDo
	WriteDB() IPaymentExpireRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPaymentExpireRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPaymentExpireRecordDo
	Not(conds ...gen.Condition) IPaymentExpireRecordDo
	Or(conds ...gen.Condition) IPaymentExpireRecordDo
	Select(conds ...field.Expr) IPaymentExpireRecordDo
	Where(conds ...gen.Condition) IPaymentExpireRecordDo
	Order(conds ...field.Expr) IPaymentExpireRecordDo
	Distinct(cols ...field.Expr) IPaymentExpireRecordDo
	Omit(cols ...field.Expr) IPaymentExpireRecordDo
	Join(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo
	Group(cols ...field.Expr) IPaymentExpireRecordDo
	Having(conds ...gen.Condition) IPaymentExpireRecordDo
	Limit(limit int) IPaymentExpireRecordDo
	Offset(offset int) IPaymentExpireRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentExpireRecordDo
	Unscoped() IPaymentExpireRecordDo
	Create(values ...*model.PaymentExpireRecord) error
	CreateInBatches(values []*model.PaymentExpireRecord, batchSize int) error
	Save(values ...*model.PaymentExpireRecord) error
	First() (*model.PaymentExpireRecord, error)
	Take() (*model.PaymentExpireRecord, error)
	Last() (*model.PaymentExpireRecord, error)
	Find() ([]*model.PaymentExpireRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentExpireRecord, err error)
	FindInBatches(result *[]*model.PaymentExpireRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PaymentExpireRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPaymentExpireRecordDo
	Assign(attrs ...field.AssignExpr) IPaymentExpireRecordDo
	Joins(fields ...field.RelationField) IPaymentExpireRecordDo
	Preload(fields ...field.RelationField) IPaymentExpireRecordDo
	FirstOrInit() (*model.PaymentExpireRecord, error)
	FirstOrCreate() (*model.PaymentExpireRecord, error)
	FindByPage(offset int, limit int) (result []*model.PaymentExpireRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPaymentExpireRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p paymentExpireRecordDo) Debug() IPaymentExpireRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentExpireRecordDo) WithContext(ctx context.Context) IPaymentExpireRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentExpireRecordDo) ReadDB() IPaymentExpireRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentExpireRecordDo) WriteDB() IPaymentExpireRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentExpireRecordDo) Session(config *gorm.Session) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentExpireRecordDo) Clauses(conds ...clause.Expression) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentExpireRecordDo) Returning(value interface{}, columns ...string) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentExpireRecordDo) Not(conds ...gen.Condition) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentExpireRecordDo) Or(conds ...gen.Condition) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentExpireRecordDo) Select(conds ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentExpireRecordDo) Where(conds ...gen.Condition) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentExpireRecordDo) Order(conds ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentExpireRecordDo) Distinct(cols ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentExpireRecordDo) Omit(cols ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentExpireRecordDo) Join(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentExpireRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentExpireRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentExpireRecordDo) Group(cols ...field.Expr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentExpireRecordDo) Having(conds ...gen.Condition) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentExpireRecordDo) Limit(limit int) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentExpireRecordDo) Offset(offset int) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentExpireRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentExpireRecordDo) Unscoped() IPaymentExpireRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentExpireRecordDo) Create(values ...*model.PaymentExpireRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentExpireRecordDo) CreateInBatches(values []*model.PaymentExpireRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentExpireRecordDo) Save(values ...*model.PaymentExpireRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentExpireRecordDo) First() (*model.PaymentExpireRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentExpireRecord), nil
	}
}

func (p paymentExpireRecordDo) Take() (*model.PaymentExpireRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentExpireRecord), nil
	}
}

func (p paymentExpireRecordDo) Last() (*model.PaymentExpireRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentExpireRecord), nil
	}
}

func (p paymentExpireRecordDo) Find() ([]*model.PaymentExpireRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentExpireRecord), err
}

func (p paymentExpireRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentExpireRecord, err error) {
	buf := make([]*model.PaymentExpireRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentExpireRecordDo) FindInBatches(result *[]*model.PaymentExpireRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentExpireRecordDo) Attrs(attrs ...field.AssignExpr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentExpireRecordDo) Assign(attrs ...field.AssignExpr) IPaymentExpireRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentExpireRecordDo) Joins(fields ...field.RelationField) IPaymentExpireRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentExpireRecordDo) Preload(fields ...field.RelationField) IPaymentExpireRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentExpireRecordDo) FirstOrInit() (*model.PaymentExpireRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentExpireRecord), nil
	}
}

func (p paymentExpireRecordDo) FirstOrCreate() (*model.PaymentExpireRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentExpireRecord), nil
	}
}

func (p paymentExpireRecordDo) FindByPage(offset int, limit int) (result []*model.PaymentExpireRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentExpireRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentExpireRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentExpireRecordDo) Delete(models ...*model.PaymentExpireRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentExpireRecordDo) withDO(do gen.Dao) *paymentExpireRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
