// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newRefundOrderProduct(db *gorm.DB, opts ...gen.DOOption) refundOrderProduct {
	_refundOrderProduct := refundOrderProduct{}

	_refundOrderProduct.refundOrderProductDo.UseDB(db, opts...)
	_refundOrderProduct.refundOrderProductDo.UseModel(&model.RefundOrderProduct{})

	tableName := _refundOrderProduct.refundOrderProductDo.TableName()
	_refundOrderProduct.ALL = field.NewAsterisk(tableName)
	_refundOrderProduct.ID = field.NewInt64(tableName, "id")
	_refundOrderProduct.Name = field.NewString(tableName, "name")
	_refundOrderProduct.Quantity = field.NewInt64(tableName, "quantity")
	_refundOrderProduct.Price = field.NewInt64(tableName, "price")
	_refundOrderProduct.Sku = field.NewString(tableName, "sku")
	_refundOrderProduct.Desc = field.NewString(tableName, "desc")
	_refundOrderProduct.URL = field.NewString(tableName, "url")
	_refundOrderProduct.OrderNo = field.NewString(tableName, "order_no")
	_refundOrderProduct.RefundNo = field.NewString(tableName, "refund_no")
	_refundOrderProduct.CreatedAt = field.NewTime(tableName, "created_at")
	_refundOrderProduct.UpdatedAt = field.NewTime(tableName, "updated_at")

	_refundOrderProduct.fillFieldMap()

	return _refundOrderProduct
}

// refundOrderProduct 退款详情
type refundOrderProduct struct {
	refundOrderProductDo refundOrderProductDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String // 订单标题
	Quantity  field.Int64  // 购买数量
	Price     field.Int64  // 单价
	Sku       field.String // 商品sku
	Desc      field.String // 商品描述
	URL       field.String // 商品链接
	OrderNo   field.String // 订单号
	RefundNo  field.String // 支付系统交易号
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (r refundOrderProduct) Table(newTableName string) *refundOrderProduct {
	r.refundOrderProductDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refundOrderProduct) As(alias string) *refundOrderProduct {
	r.refundOrderProductDo.DO = *(r.refundOrderProductDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refundOrderProduct) updateTableName(table string) *refundOrderProduct {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Name = field.NewString(table, "name")
	r.Quantity = field.NewInt64(table, "quantity")
	r.Price = field.NewInt64(table, "price")
	r.Sku = field.NewString(table, "sku")
	r.Desc = field.NewString(table, "desc")
	r.URL = field.NewString(table, "url")
	r.OrderNo = field.NewString(table, "order_no")
	r.RefundNo = field.NewString(table, "refund_no")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *refundOrderProduct) WithContext(ctx context.Context) IRefundOrderProductDo {
	return r.refundOrderProductDo.WithContext(ctx)
}

func (r refundOrderProduct) TableName() string { return r.refundOrderProductDo.TableName() }

func (r refundOrderProduct) Alias() string { return r.refundOrderProductDo.Alias() }

func (r refundOrderProduct) Columns(cols ...field.Expr) gen.Columns {
	return r.refundOrderProductDo.Columns(cols...)
}

func (r *refundOrderProduct) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refundOrderProduct) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["name"] = r.Name
	r.fieldMap["quantity"] = r.Quantity
	r.fieldMap["price"] = r.Price
	r.fieldMap["sku"] = r.Sku
	r.fieldMap["desc"] = r.Desc
	r.fieldMap["url"] = r.URL
	r.fieldMap["order_no"] = r.OrderNo
	r.fieldMap["refund_no"] = r.RefundNo
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r refundOrderProduct) clone(db *gorm.DB) refundOrderProduct {
	r.refundOrderProductDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refundOrderProduct) replaceDB(db *gorm.DB) refundOrderProduct {
	r.refundOrderProductDo.ReplaceDB(db)
	return r
}

type refundOrderProductDo struct{ gen.DO }

type IRefundOrderProductDo interface {
	gen.SubQuery
	Debug() IRefundOrderProductDo
	WithContext(ctx context.Context) IRefundOrderProductDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRefundOrderProductDo
	WriteDB() IRefundOrderProductDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRefundOrderProductDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRefundOrderProductDo
	Not(conds ...gen.Condition) IRefundOrderProductDo
	Or(conds ...gen.Condition) IRefundOrderProductDo
	Select(conds ...field.Expr) IRefundOrderProductDo
	Where(conds ...gen.Condition) IRefundOrderProductDo
	Order(conds ...field.Expr) IRefundOrderProductDo
	Distinct(cols ...field.Expr) IRefundOrderProductDo
	Omit(cols ...field.Expr) IRefundOrderProductDo
	Join(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo
	Group(cols ...field.Expr) IRefundOrderProductDo
	Having(conds ...gen.Condition) IRefundOrderProductDo
	Limit(limit int) IRefundOrderProductDo
	Offset(offset int) IRefundOrderProductDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRefundOrderProductDo
	Unscoped() IRefundOrderProductDo
	Create(values ...*model.RefundOrderProduct) error
	CreateInBatches(values []*model.RefundOrderProduct, batchSize int) error
	Save(values ...*model.RefundOrderProduct) error
	First() (*model.RefundOrderProduct, error)
	Take() (*model.RefundOrderProduct, error)
	Last() (*model.RefundOrderProduct, error)
	Find() ([]*model.RefundOrderProduct, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RefundOrderProduct, err error)
	FindInBatches(result *[]*model.RefundOrderProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RefundOrderProduct) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRefundOrderProductDo
	Assign(attrs ...field.AssignExpr) IRefundOrderProductDo
	Joins(fields ...field.RelationField) IRefundOrderProductDo
	Preload(fields ...field.RelationField) IRefundOrderProductDo
	FirstOrInit() (*model.RefundOrderProduct, error)
	FirstOrCreate() (*model.RefundOrderProduct, error)
	FindByPage(offset int, limit int) (result []*model.RefundOrderProduct, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRefundOrderProductDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r refundOrderProductDo) Debug() IRefundOrderProductDo {
	return r.withDO(r.DO.Debug())
}

func (r refundOrderProductDo) WithContext(ctx context.Context) IRefundOrderProductDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refundOrderProductDo) ReadDB() IRefundOrderProductDo {
	return r.Clauses(dbresolver.Read)
}

func (r refundOrderProductDo) WriteDB() IRefundOrderProductDo {
	return r.Clauses(dbresolver.Write)
}

func (r refundOrderProductDo) Session(config *gorm.Session) IRefundOrderProductDo {
	return r.withDO(r.DO.Session(config))
}

func (r refundOrderProductDo) Clauses(conds ...clause.Expression) IRefundOrderProductDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refundOrderProductDo) Returning(value interface{}, columns ...string) IRefundOrderProductDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refundOrderProductDo) Not(conds ...gen.Condition) IRefundOrderProductDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refundOrderProductDo) Or(conds ...gen.Condition) IRefundOrderProductDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refundOrderProductDo) Select(conds ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refundOrderProductDo) Where(conds ...gen.Condition) IRefundOrderProductDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refundOrderProductDo) Order(conds ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refundOrderProductDo) Distinct(cols ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refundOrderProductDo) Omit(cols ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refundOrderProductDo) Join(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refundOrderProductDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refundOrderProductDo) RightJoin(table schema.Tabler, on ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refundOrderProductDo) Group(cols ...field.Expr) IRefundOrderProductDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refundOrderProductDo) Having(conds ...gen.Condition) IRefundOrderProductDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refundOrderProductDo) Limit(limit int) IRefundOrderProductDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refundOrderProductDo) Offset(offset int) IRefundOrderProductDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refundOrderProductDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRefundOrderProductDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refundOrderProductDo) Unscoped() IRefundOrderProductDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refundOrderProductDo) Create(values ...*model.RefundOrderProduct) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refundOrderProductDo) CreateInBatches(values []*model.RefundOrderProduct, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refundOrderProductDo) Save(values ...*model.RefundOrderProduct) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refundOrderProductDo) First() (*model.RefundOrderProduct, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrderProduct), nil
	}
}

func (r refundOrderProductDo) Take() (*model.RefundOrderProduct, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrderProduct), nil
	}
}

func (r refundOrderProductDo) Last() (*model.RefundOrderProduct, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrderProduct), nil
	}
}

func (r refundOrderProductDo) Find() ([]*model.RefundOrderProduct, error) {
	result, err := r.DO.Find()
	return result.([]*model.RefundOrderProduct), err
}

func (r refundOrderProductDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RefundOrderProduct, err error) {
	buf := make([]*model.RefundOrderProduct, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refundOrderProductDo) FindInBatches(result *[]*model.RefundOrderProduct, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refundOrderProductDo) Attrs(attrs ...field.AssignExpr) IRefundOrderProductDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refundOrderProductDo) Assign(attrs ...field.AssignExpr) IRefundOrderProductDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refundOrderProductDo) Joins(fields ...field.RelationField) IRefundOrderProductDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refundOrderProductDo) Preload(fields ...field.RelationField) IRefundOrderProductDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refundOrderProductDo) FirstOrInit() (*model.RefundOrderProduct, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrderProduct), nil
	}
}

func (r refundOrderProductDo) FirstOrCreate() (*model.RefundOrderProduct, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrderProduct), nil
	}
}

func (r refundOrderProductDo) FindByPage(offset int, limit int) (result []*model.RefundOrderProduct, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refundOrderProductDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refundOrderProductDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refundOrderProductDo) Delete(models ...*model.RefundOrderProduct) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refundOrderProductDo) withDO(do gen.Dao) *refundOrderProductDo {
	r.DO = *do.(*gen.DO)
	return r
}
