// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newRefundOrder(db *gorm.DB, opts ...gen.DOOption) refundOrder {
	_refundOrder := refundOrder{}

	_refundOrder.refundOrderDo.UseDB(db, opts...)
	_refundOrder.refundOrderDo.UseModel(&model.RefundOrder{})

	tableName := _refundOrder.refundOrderDo.TableName()
	_refundOrder.ALL = field.NewAsterisk(tableName)
	_refundOrder.ID = field.NewInt64(tableName, "id")
	_refundOrder.PaymentAccountNo = field.NewString(tableName, "payment_account_no")
	_refundOrder.AppNo = field.NewString(tableName, "app_no")
	_refundOrder.MchNo = field.NewString(tableName, "mch_no")
	_refundOrder.Resaon = field.NewString(tableName, "resaon")
	_refundOrder.OrderNo = field.NewString(tableName, "order_no")
	_refundOrder.TradeNo = field.NewString(tableName, "trade_no")
	_refundOrder.RefundTradeNo = field.NewString(tableName, "refund_trade_no")
	_refundOrder.RefundNo = field.NewString(tableName, "refund_no")
	_refundOrder.Device = field.NewString(tableName, "device")
	_refundOrder.RefundAmount = field.NewInt64(tableName, "refund_amount")
	_refundOrder.PaymentAmount = field.NewInt64(tableName, "payment_amount")
	_refundOrder.Currency = field.NewString(tableName, "currency")
	_refundOrder.Status = field.NewInt64(tableName, "status")
	_refundOrder.StatusFrom = field.NewString(tableName, "status_from")
	_refundOrder.NotifyURL = field.NewString(tableName, "notify_url")
	_refundOrder.NotifyStatus = field.NewInt64(tableName, "notify_status")
	_refundOrder.OutMchTradeNo = field.NewString(tableName, "out_mch_trade_no")
	_refundOrder.ExtParam = field.NewString(tableName, "ext_param")
	_refundOrder.SuccessTime = field.NewTime(tableName, "success_time")
	_refundOrder.RefundFrom = field.NewInt64(tableName, "refund_from")
	_refundOrder.ThirdMsg = field.NewString(tableName, "third_msg")
	_refundOrder.CreatedAt = field.NewTime(tableName, "created_at")
	_refundOrder.UpdatedAt = field.NewTime(tableName, "updated_at")

	_refundOrder.fillFieldMap()

	return _refundOrder
}

// refundOrder 支付方式
type refundOrder struct {
	refundOrderDo refundOrderDo

	ALL              field.Asterisk
	ID               field.Int64
	PaymentAccountNo field.String // payemnt_account_no
	AppNo            field.String // 应用编号
	MchNo            field.String // 商户编号
	Resaon           field.String // 退款原因
	OrderNo          field.String // 订单号
	TradeNo          field.String // 支付系统交易号
	RefundTradeNo    field.String // 渠道退款号
	RefundNo         field.String // 支付系统交易号
	Device           field.String // 支付系统交易号
	RefundAmount     field.Int64  // 退款金额分单位
	PaymentAmount    field.Int64  // 订单实付金额分单位
	Currency         field.String // 币种
	Status           field.Int64  // 退款状态
	StatusFrom       field.String // 状态修改来源API|WEBHOOK|ADMIN
	NotifyURL        field.String // 异步通知url
	NotifyStatus     field.Int64  // 1待通知， 2已通知
	OutMchTradeNo    field.String // 外部请求退款单号
	ExtParam         field.String // 扩展参数
	SuccessTime      field.Time   // 成功时间
	RefundFrom       field.Int64  // 发起 1 外部接口发起，2 后台发起
	ThirdMsg         field.String // 三方返回错误原因
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (r refundOrder) Table(newTableName string) *refundOrder {
	r.refundOrderDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r refundOrder) As(alias string) *refundOrder {
	r.refundOrderDo.DO = *(r.refundOrderDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *refundOrder) updateTableName(table string) *refundOrder {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.PaymentAccountNo = field.NewString(table, "payment_account_no")
	r.AppNo = field.NewString(table, "app_no")
	r.MchNo = field.NewString(table, "mch_no")
	r.Resaon = field.NewString(table, "resaon")
	r.OrderNo = field.NewString(table, "order_no")
	r.TradeNo = field.NewString(table, "trade_no")
	r.RefundTradeNo = field.NewString(table, "refund_trade_no")
	r.RefundNo = field.NewString(table, "refund_no")
	r.Device = field.NewString(table, "device")
	r.RefundAmount = field.NewInt64(table, "refund_amount")
	r.PaymentAmount = field.NewInt64(table, "payment_amount")
	r.Currency = field.NewString(table, "currency")
	r.Status = field.NewInt64(table, "status")
	r.StatusFrom = field.NewString(table, "status_from")
	r.NotifyURL = field.NewString(table, "notify_url")
	r.NotifyStatus = field.NewInt64(table, "notify_status")
	r.OutMchTradeNo = field.NewString(table, "out_mch_trade_no")
	r.ExtParam = field.NewString(table, "ext_param")
	r.SuccessTime = field.NewTime(table, "success_time")
	r.RefundFrom = field.NewInt64(table, "refund_from")
	r.ThirdMsg = field.NewString(table, "third_msg")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *refundOrder) WithContext(ctx context.Context) IRefundOrderDo {
	return r.refundOrderDo.WithContext(ctx)
}

func (r refundOrder) TableName() string { return r.refundOrderDo.TableName() }

func (r refundOrder) Alias() string { return r.refundOrderDo.Alias() }

func (r refundOrder) Columns(cols ...field.Expr) gen.Columns { return r.refundOrderDo.Columns(cols...) }

func (r *refundOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *refundOrder) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 24)
	r.fieldMap["id"] = r.ID
	r.fieldMap["payment_account_no"] = r.PaymentAccountNo
	r.fieldMap["app_no"] = r.AppNo
	r.fieldMap["mch_no"] = r.MchNo
	r.fieldMap["resaon"] = r.Resaon
	r.fieldMap["order_no"] = r.OrderNo
	r.fieldMap["trade_no"] = r.TradeNo
	r.fieldMap["refund_trade_no"] = r.RefundTradeNo
	r.fieldMap["refund_no"] = r.RefundNo
	r.fieldMap["device"] = r.Device
	r.fieldMap["refund_amount"] = r.RefundAmount
	r.fieldMap["payment_amount"] = r.PaymentAmount
	r.fieldMap["currency"] = r.Currency
	r.fieldMap["status"] = r.Status
	r.fieldMap["status_from"] = r.StatusFrom
	r.fieldMap["notify_url"] = r.NotifyURL
	r.fieldMap["notify_status"] = r.NotifyStatus
	r.fieldMap["out_mch_trade_no"] = r.OutMchTradeNo
	r.fieldMap["ext_param"] = r.ExtParam
	r.fieldMap["success_time"] = r.SuccessTime
	r.fieldMap["refund_from"] = r.RefundFrom
	r.fieldMap["third_msg"] = r.ThirdMsg
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r refundOrder) clone(db *gorm.DB) refundOrder {
	r.refundOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r refundOrder) replaceDB(db *gorm.DB) refundOrder {
	r.refundOrderDo.ReplaceDB(db)
	return r
}

type refundOrderDo struct{ gen.DO }

type IRefundOrderDo interface {
	gen.SubQuery
	Debug() IRefundOrderDo
	WithContext(ctx context.Context) IRefundOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRefundOrderDo
	WriteDB() IRefundOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRefundOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRefundOrderDo
	Not(conds ...gen.Condition) IRefundOrderDo
	Or(conds ...gen.Condition) IRefundOrderDo
	Select(conds ...field.Expr) IRefundOrderDo
	Where(conds ...gen.Condition) IRefundOrderDo
	Order(conds ...field.Expr) IRefundOrderDo
	Distinct(cols ...field.Expr) IRefundOrderDo
	Omit(cols ...field.Expr) IRefundOrderDo
	Join(table schema.Tabler, on ...field.Expr) IRefundOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRefundOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRefundOrderDo
	Group(cols ...field.Expr) IRefundOrderDo
	Having(conds ...gen.Condition) IRefundOrderDo
	Limit(limit int) IRefundOrderDo
	Offset(offset int) IRefundOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRefundOrderDo
	Unscoped() IRefundOrderDo
	Create(values ...*model.RefundOrder) error
	CreateInBatches(values []*model.RefundOrder, batchSize int) error
	Save(values ...*model.RefundOrder) error
	First() (*model.RefundOrder, error)
	Take() (*model.RefundOrder, error)
	Last() (*model.RefundOrder, error)
	Find() ([]*model.RefundOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RefundOrder, err error)
	FindInBatches(result *[]*model.RefundOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RefundOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRefundOrderDo
	Assign(attrs ...field.AssignExpr) IRefundOrderDo
	Joins(fields ...field.RelationField) IRefundOrderDo
	Preload(fields ...field.RelationField) IRefundOrderDo
	FirstOrInit() (*model.RefundOrder, error)
	FirstOrCreate() (*model.RefundOrder, error)
	FindByPage(offset int, limit int) (result []*model.RefundOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRefundOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r refundOrderDo) Debug() IRefundOrderDo {
	return r.withDO(r.DO.Debug())
}

func (r refundOrderDo) WithContext(ctx context.Context) IRefundOrderDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r refundOrderDo) ReadDB() IRefundOrderDo {
	return r.Clauses(dbresolver.Read)
}

func (r refundOrderDo) WriteDB() IRefundOrderDo {
	return r.Clauses(dbresolver.Write)
}

func (r refundOrderDo) Session(config *gorm.Session) IRefundOrderDo {
	return r.withDO(r.DO.Session(config))
}

func (r refundOrderDo) Clauses(conds ...clause.Expression) IRefundOrderDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r refundOrderDo) Returning(value interface{}, columns ...string) IRefundOrderDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r refundOrderDo) Not(conds ...gen.Condition) IRefundOrderDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r refundOrderDo) Or(conds ...gen.Condition) IRefundOrderDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r refundOrderDo) Select(conds ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r refundOrderDo) Where(conds ...gen.Condition) IRefundOrderDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r refundOrderDo) Order(conds ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r refundOrderDo) Distinct(cols ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r refundOrderDo) Omit(cols ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r refundOrderDo) Join(table schema.Tabler, on ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r refundOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r refundOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r refundOrderDo) Group(cols ...field.Expr) IRefundOrderDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r refundOrderDo) Having(conds ...gen.Condition) IRefundOrderDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r refundOrderDo) Limit(limit int) IRefundOrderDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r refundOrderDo) Offset(offset int) IRefundOrderDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r refundOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRefundOrderDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r refundOrderDo) Unscoped() IRefundOrderDo {
	return r.withDO(r.DO.Unscoped())
}

func (r refundOrderDo) Create(values ...*model.RefundOrder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r refundOrderDo) CreateInBatches(values []*model.RefundOrder, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r refundOrderDo) Save(values ...*model.RefundOrder) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r refundOrderDo) First() (*model.RefundOrder, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrder), nil
	}
}

func (r refundOrderDo) Take() (*model.RefundOrder, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrder), nil
	}
}

func (r refundOrderDo) Last() (*model.RefundOrder, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrder), nil
	}
}

func (r refundOrderDo) Find() ([]*model.RefundOrder, error) {
	result, err := r.DO.Find()
	return result.([]*model.RefundOrder), err
}

func (r refundOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RefundOrder, err error) {
	buf := make([]*model.RefundOrder, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r refundOrderDo) FindInBatches(result *[]*model.RefundOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r refundOrderDo) Attrs(attrs ...field.AssignExpr) IRefundOrderDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r refundOrderDo) Assign(attrs ...field.AssignExpr) IRefundOrderDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r refundOrderDo) Joins(fields ...field.RelationField) IRefundOrderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r refundOrderDo) Preload(fields ...field.RelationField) IRefundOrderDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r refundOrderDo) FirstOrInit() (*model.RefundOrder, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrder), nil
	}
}

func (r refundOrderDo) FirstOrCreate() (*model.RefundOrder, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RefundOrder), nil
	}
}

func (r refundOrderDo) FindByPage(offset int, limit int) (result []*model.RefundOrder, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r refundOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r refundOrderDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r refundOrderDo) Delete(models ...*model.RefundOrder) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *refundOrderDo) withDO(do gen.Dao) *refundOrderDo {
	r.DO = *do.(*gen.DO)
	return r
}
