// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newRouterAccountStatistic(db *gorm.DB, opts ...gen.DOOption) routerAccountStatistic {
	_routerAccountStatistic := routerAccountStatistic{}

	_routerAccountStatistic.routerAccountStatisticDo.UseDB(db, opts...)
	_routerAccountStatistic.routerAccountStatisticDo.UseModel(&model.RouterAccountStatistic{})

	tableName := _routerAccountStatistic.routerAccountStatisticDo.TableName()
	_routerAccountStatistic.ALL = field.NewAsterisk(tableName)
	_routerAccountStatistic.ID = field.NewInt64(tableName, "id")
	_routerAccountStatistic.AppNo = field.NewString(tableName, "app_no")
	_routerAccountStatistic.AccountNo = field.NewString(tableName, "account_no")
	_routerAccountStatistic.StatisticDate = field.NewTime(tableName, "statistic_date")
	_routerAccountStatistic.TotalRequests = field.NewInt64(tableName, "total_requests")
	_routerAccountStatistic.SuccessRequests = field.NewInt64(tableName, "success_requests")
	_routerAccountStatistic.FailureRequests = field.NewInt64(tableName, "failure_requests")
	_routerAccountStatistic.UserLimit = field.NewInt64(tableName, "user_limit")
	_routerAccountStatistic.CreatedAt = field.NewTime(tableName, "created_at")
	_routerAccountStatistic.UpdatedAt = field.NewTime(tableName, "updated_at")
	_routerAccountStatistic.SuccessAmount = field.NewInt64(tableName, "success_amount")
	_routerAccountStatistic.PaymentLimit = field.NewInt64(tableName, "payment_limit")

	_routerAccountStatistic.fillFieldMap()

	return _routerAccountStatistic
}

// routerAccountStatistic 路由需要的数据统计
type routerAccountStatistic struct {
	routerAccountStatisticDo routerAccountStatisticDo

	ALL             field.Asterisk
	ID              field.Int64
	AppNo           field.String // 应用编号
	AccountNo       field.String // 支付账号编号
	StatisticDate   field.Time   // 统计日期
	TotalRequests   field.Int64  // 总请求数
	SuccessRequests field.Int64  // 成功请求数
	FailureRequests field.Int64  // 失败请求数
	UserLimit       field.Int64  // 用户登录是否限制, 0 未限制，1限制
	CreatedAt       field.Time
	UpdatedAt       field.Time
	SuccessAmount   field.Int64 // 收款金额，分单位
	PaymentLimit    field.Int64 // 0 未限制，1收款被微信限制

	fieldMap map[string]field.Expr
}

func (r routerAccountStatistic) Table(newTableName string) *routerAccountStatistic {
	r.routerAccountStatisticDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r routerAccountStatistic) As(alias string) *routerAccountStatistic {
	r.routerAccountStatisticDo.DO = *(r.routerAccountStatisticDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *routerAccountStatistic) updateTableName(table string) *routerAccountStatistic {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.AppNo = field.NewString(table, "app_no")
	r.AccountNo = field.NewString(table, "account_no")
	r.StatisticDate = field.NewTime(table, "statistic_date")
	r.TotalRequests = field.NewInt64(table, "total_requests")
	r.SuccessRequests = field.NewInt64(table, "success_requests")
	r.FailureRequests = field.NewInt64(table, "failure_requests")
	r.UserLimit = field.NewInt64(table, "user_limit")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.SuccessAmount = field.NewInt64(table, "success_amount")
	r.PaymentLimit = field.NewInt64(table, "payment_limit")

	r.fillFieldMap()

	return r
}

func (r *routerAccountStatistic) WithContext(ctx context.Context) IRouterAccountStatisticDo {
	return r.routerAccountStatisticDo.WithContext(ctx)
}

func (r routerAccountStatistic) TableName() string { return r.routerAccountStatisticDo.TableName() }

func (r routerAccountStatistic) Alias() string { return r.routerAccountStatisticDo.Alias() }

func (r routerAccountStatistic) Columns(cols ...field.Expr) gen.Columns {
	return r.routerAccountStatisticDo.Columns(cols...)
}

func (r *routerAccountStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *routerAccountStatistic) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["app_no"] = r.AppNo
	r.fieldMap["account_no"] = r.AccountNo
	r.fieldMap["statistic_date"] = r.StatisticDate
	r.fieldMap["total_requests"] = r.TotalRequests
	r.fieldMap["success_requests"] = r.SuccessRequests
	r.fieldMap["failure_requests"] = r.FailureRequests
	r.fieldMap["user_limit"] = r.UserLimit
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["success_amount"] = r.SuccessAmount
	r.fieldMap["payment_limit"] = r.PaymentLimit
}

func (r routerAccountStatistic) clone(db *gorm.DB) routerAccountStatistic {
	r.routerAccountStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r routerAccountStatistic) replaceDB(db *gorm.DB) routerAccountStatistic {
	r.routerAccountStatisticDo.ReplaceDB(db)
	return r
}

type routerAccountStatisticDo struct{ gen.DO }

type IRouterAccountStatisticDo interface {
	gen.SubQuery
	Debug() IRouterAccountStatisticDo
	WithContext(ctx context.Context) IRouterAccountStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRouterAccountStatisticDo
	WriteDB() IRouterAccountStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRouterAccountStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRouterAccountStatisticDo
	Not(conds ...gen.Condition) IRouterAccountStatisticDo
	Or(conds ...gen.Condition) IRouterAccountStatisticDo
	Select(conds ...field.Expr) IRouterAccountStatisticDo
	Where(conds ...gen.Condition) IRouterAccountStatisticDo
	Order(conds ...field.Expr) IRouterAccountStatisticDo
	Distinct(cols ...field.Expr) IRouterAccountStatisticDo
	Omit(cols ...field.Expr) IRouterAccountStatisticDo
	Join(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo
	Group(cols ...field.Expr) IRouterAccountStatisticDo
	Having(conds ...gen.Condition) IRouterAccountStatisticDo
	Limit(limit int) IRouterAccountStatisticDo
	Offset(offset int) IRouterAccountStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRouterAccountStatisticDo
	Unscoped() IRouterAccountStatisticDo
	Create(values ...*model.RouterAccountStatistic) error
	CreateInBatches(values []*model.RouterAccountStatistic, batchSize int) error
	Save(values ...*model.RouterAccountStatistic) error
	First() (*model.RouterAccountStatistic, error)
	Take() (*model.RouterAccountStatistic, error)
	Last() (*model.RouterAccountStatistic, error)
	Find() ([]*model.RouterAccountStatistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouterAccountStatistic, err error)
	FindInBatches(result *[]*model.RouterAccountStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RouterAccountStatistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRouterAccountStatisticDo
	Assign(attrs ...field.AssignExpr) IRouterAccountStatisticDo
	Joins(fields ...field.RelationField) IRouterAccountStatisticDo
	Preload(fields ...field.RelationField) IRouterAccountStatisticDo
	FirstOrInit() (*model.RouterAccountStatistic, error)
	FirstOrCreate() (*model.RouterAccountStatistic, error)
	FindByPage(offset int, limit int) (result []*model.RouterAccountStatistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRouterAccountStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r routerAccountStatisticDo) Debug() IRouterAccountStatisticDo {
	return r.withDO(r.DO.Debug())
}

func (r routerAccountStatisticDo) WithContext(ctx context.Context) IRouterAccountStatisticDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r routerAccountStatisticDo) ReadDB() IRouterAccountStatisticDo {
	return r.Clauses(dbresolver.Read)
}

func (r routerAccountStatisticDo) WriteDB() IRouterAccountStatisticDo {
	return r.Clauses(dbresolver.Write)
}

func (r routerAccountStatisticDo) Session(config *gorm.Session) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Session(config))
}

func (r routerAccountStatisticDo) Clauses(conds ...clause.Expression) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r routerAccountStatisticDo) Returning(value interface{}, columns ...string) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r routerAccountStatisticDo) Not(conds ...gen.Condition) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r routerAccountStatisticDo) Or(conds ...gen.Condition) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r routerAccountStatisticDo) Select(conds ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r routerAccountStatisticDo) Where(conds ...gen.Condition) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r routerAccountStatisticDo) Order(conds ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r routerAccountStatisticDo) Distinct(cols ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r routerAccountStatisticDo) Omit(cols ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r routerAccountStatisticDo) Join(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r routerAccountStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r routerAccountStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r routerAccountStatisticDo) Group(cols ...field.Expr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r routerAccountStatisticDo) Having(conds ...gen.Condition) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r routerAccountStatisticDo) Limit(limit int) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r routerAccountStatisticDo) Offset(offset int) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r routerAccountStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r routerAccountStatisticDo) Unscoped() IRouterAccountStatisticDo {
	return r.withDO(r.DO.Unscoped())
}

func (r routerAccountStatisticDo) Create(values ...*model.RouterAccountStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r routerAccountStatisticDo) CreateInBatches(values []*model.RouterAccountStatistic, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r routerAccountStatisticDo) Save(values ...*model.RouterAccountStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r routerAccountStatisticDo) First() (*model.RouterAccountStatistic, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouterAccountStatistic), nil
	}
}

func (r routerAccountStatisticDo) Take() (*model.RouterAccountStatistic, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouterAccountStatistic), nil
	}
}

func (r routerAccountStatisticDo) Last() (*model.RouterAccountStatistic, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouterAccountStatistic), nil
	}
}

func (r routerAccountStatisticDo) Find() ([]*model.RouterAccountStatistic, error) {
	result, err := r.DO.Find()
	return result.([]*model.RouterAccountStatistic), err
}

func (r routerAccountStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouterAccountStatistic, err error) {
	buf := make([]*model.RouterAccountStatistic, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r routerAccountStatisticDo) FindInBatches(result *[]*model.RouterAccountStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r routerAccountStatisticDo) Attrs(attrs ...field.AssignExpr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r routerAccountStatisticDo) Assign(attrs ...field.AssignExpr) IRouterAccountStatisticDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r routerAccountStatisticDo) Joins(fields ...field.RelationField) IRouterAccountStatisticDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r routerAccountStatisticDo) Preload(fields ...field.RelationField) IRouterAccountStatisticDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r routerAccountStatisticDo) FirstOrInit() (*model.RouterAccountStatistic, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouterAccountStatistic), nil
	}
}

func (r routerAccountStatisticDo) FirstOrCreate() (*model.RouterAccountStatistic, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouterAccountStatistic), nil
	}
}

func (r routerAccountStatisticDo) FindByPage(offset int, limit int) (result []*model.RouterAccountStatistic, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r routerAccountStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r routerAccountStatisticDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r routerAccountStatisticDo) Delete(models ...*model.RouterAccountStatistic) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *routerAccountStatisticDo) withDO(do gen.Dao) *routerAccountStatisticDo {
	r.DO = *do.(*gen.DO)
	return r
}
