// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newStatistic(db *gorm.DB, opts ...gen.DOOption) statistic {
	_statistic := statistic{}

	_statistic.statisticDo.UseDB(db, opts...)
	_statistic.statisticDo.UseModel(&model.Statistic{})

	tableName := _statistic.statisticDo.TableName()
	_statistic.ALL = field.NewAsterisk(tableName)
	_statistic.ID = field.NewInt64(tableName, "id")
	_statistic.AppNo = field.NewString(tableName, "app_no")
	_statistic.MchNo = field.NewString(tableName, "mch_no")
	_statistic.StatisticDate = field.NewTime(tableName, "statistic_date")
	_statistic.StatisticTag = field.NewString(tableName, "statistic_tag")
	_statistic.StatisticKey = field.NewString(tableName, "statistic_key")
	_statistic.StatisticLabel = field.NewString(tableName, "statistic_label")
	_statistic.Statistic = field.NewInt64(tableName, "statistic")
	_statistic.CreatedAt = field.NewTime(tableName, "created_at")
	_statistic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_statistic.fillFieldMap()

	return _statistic
}

// statistic 数据统计
type statistic struct {
	statisticDo statisticDo

	ALL            field.Asterisk
	ID             field.Int64
	AppNo          field.String // 应用编号
	MchNo          field.String // 商户编号
	StatisticDate  field.Time   // 统计日期
	StatisticTag   field.String // 标签
	StatisticKey   field.String // 标签下某个统计项
	StatisticLabel field.String // 标签下某个统计项名字
	Statistic      field.Int64  // 统计计数
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (s statistic) Table(newTableName string) *statistic {
	s.statisticDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s statistic) As(alias string) *statistic {
	s.statisticDo.DO = *(s.statisticDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *statistic) updateTableName(table string) *statistic {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.AppNo = field.NewString(table, "app_no")
	s.MchNo = field.NewString(table, "mch_no")
	s.StatisticDate = field.NewTime(table, "statistic_date")
	s.StatisticTag = field.NewString(table, "statistic_tag")
	s.StatisticKey = field.NewString(table, "statistic_key")
	s.StatisticLabel = field.NewString(table, "statistic_label")
	s.Statistic = field.NewInt64(table, "statistic")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *statistic) WithContext(ctx context.Context) IStatisticDo {
	return s.statisticDo.WithContext(ctx)
}

func (s statistic) TableName() string { return s.statisticDo.TableName() }

func (s statistic) Alias() string { return s.statisticDo.Alias() }

func (s statistic) Columns(cols ...field.Expr) gen.Columns { return s.statisticDo.Columns(cols...) }

func (s *statistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *statistic) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["app_no"] = s.AppNo
	s.fieldMap["mch_no"] = s.MchNo
	s.fieldMap["statistic_date"] = s.StatisticDate
	s.fieldMap["statistic_tag"] = s.StatisticTag
	s.fieldMap["statistic_key"] = s.StatisticKey
	s.fieldMap["statistic_label"] = s.StatisticLabel
	s.fieldMap["statistic"] = s.Statistic
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s statistic) clone(db *gorm.DB) statistic {
	s.statisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s statistic) replaceDB(db *gorm.DB) statistic {
	s.statisticDo.ReplaceDB(db)
	return s
}

type statisticDo struct{ gen.DO }

type IStatisticDo interface {
	gen.SubQuery
	Debug() IStatisticDo
	WithContext(ctx context.Context) IStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStatisticDo
	WriteDB() IStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStatisticDo
	Not(conds ...gen.Condition) IStatisticDo
	Or(conds ...gen.Condition) IStatisticDo
	Select(conds ...field.Expr) IStatisticDo
	Where(conds ...gen.Condition) IStatisticDo
	Order(conds ...field.Expr) IStatisticDo
	Distinct(cols ...field.Expr) IStatisticDo
	Omit(cols ...field.Expr) IStatisticDo
	Join(table schema.Tabler, on ...field.Expr) IStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStatisticDo
	Group(cols ...field.Expr) IStatisticDo
	Having(conds ...gen.Condition) IStatisticDo
	Limit(limit int) IStatisticDo
	Offset(offset int) IStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStatisticDo
	Unscoped() IStatisticDo
	Create(values ...*model.Statistic) error
	CreateInBatches(values []*model.Statistic, batchSize int) error
	Save(values ...*model.Statistic) error
	First() (*model.Statistic, error)
	Take() (*model.Statistic, error)
	Last() (*model.Statistic, error)
	Find() ([]*model.Statistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Statistic, err error)
	FindInBatches(result *[]*model.Statistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Statistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStatisticDo
	Assign(attrs ...field.AssignExpr) IStatisticDo
	Joins(fields ...field.RelationField) IStatisticDo
	Preload(fields ...field.RelationField) IStatisticDo
	FirstOrInit() (*model.Statistic, error)
	FirstOrCreate() (*model.Statistic, error)
	FindByPage(offset int, limit int) (result []*model.Statistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s statisticDo) Debug() IStatisticDo {
	return s.withDO(s.DO.Debug())
}

func (s statisticDo) WithContext(ctx context.Context) IStatisticDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s statisticDo) ReadDB() IStatisticDo {
	return s.Clauses(dbresolver.Read)
}

func (s statisticDo) WriteDB() IStatisticDo {
	return s.Clauses(dbresolver.Write)
}

func (s statisticDo) Session(config *gorm.Session) IStatisticDo {
	return s.withDO(s.DO.Session(config))
}

func (s statisticDo) Clauses(conds ...clause.Expression) IStatisticDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s statisticDo) Returning(value interface{}, columns ...string) IStatisticDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s statisticDo) Not(conds ...gen.Condition) IStatisticDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s statisticDo) Or(conds ...gen.Condition) IStatisticDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s statisticDo) Select(conds ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s statisticDo) Where(conds ...gen.Condition) IStatisticDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s statisticDo) Order(conds ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s statisticDo) Distinct(cols ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s statisticDo) Omit(cols ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s statisticDo) Join(table schema.Tabler, on ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s statisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s statisticDo) RightJoin(table schema.Tabler, on ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s statisticDo) Group(cols ...field.Expr) IStatisticDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s statisticDo) Having(conds ...gen.Condition) IStatisticDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s statisticDo) Limit(limit int) IStatisticDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s statisticDo) Offset(offset int) IStatisticDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s statisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStatisticDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s statisticDo) Unscoped() IStatisticDo {
	return s.withDO(s.DO.Unscoped())
}

func (s statisticDo) Create(values ...*model.Statistic) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s statisticDo) CreateInBatches(values []*model.Statistic, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s statisticDo) Save(values ...*model.Statistic) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s statisticDo) First() (*model.Statistic, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statistic), nil
	}
}

func (s statisticDo) Take() (*model.Statistic, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statistic), nil
	}
}

func (s statisticDo) Last() (*model.Statistic, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statistic), nil
	}
}

func (s statisticDo) Find() ([]*model.Statistic, error) {
	result, err := s.DO.Find()
	return result.([]*model.Statistic), err
}

func (s statisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Statistic, err error) {
	buf := make([]*model.Statistic, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s statisticDo) FindInBatches(result *[]*model.Statistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s statisticDo) Attrs(attrs ...field.AssignExpr) IStatisticDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s statisticDo) Assign(attrs ...field.AssignExpr) IStatisticDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s statisticDo) Joins(fields ...field.RelationField) IStatisticDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s statisticDo) Preload(fields ...field.RelationField) IStatisticDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s statisticDo) FirstOrInit() (*model.Statistic, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statistic), nil
	}
}

func (s statisticDo) FirstOrCreate() (*model.Statistic, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Statistic), nil
	}
}

func (s statisticDo) FindByPage(offset int, limit int) (result []*model.Statistic, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s statisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s statisticDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s statisticDo) Delete(models ...*model.Statistic) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *statisticDo) withDO(do gen.Dao) *statisticDo {
	s.DO = *do.(*gen.DO)
	return s
}
