// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/lihongsheng/pay-gateway/plugin/payment/repo/model"
)

func newTradeStatistic(db *gorm.DB, opts ...gen.DOOption) tradeStatistic {
	_tradeStatistic := tradeStatistic{}

	_tradeStatistic.tradeStatisticDo.UseDB(db, opts...)
	_tradeStatistic.tradeStatisticDo.UseModel(&model.TradeStatistic{})

	tableName := _tradeStatistic.tradeStatisticDo.TableName()
	_tradeStatistic.ALL = field.NewAsterisk(tableName)
	_tradeStatistic.ID = field.NewInt64(tableName, "id")
	_tradeStatistic.AppNo = field.NewString(tableName, "app_no")
	_tradeStatistic.AccountNo = field.NewString(tableName, "account_no")
	_tradeStatistic.MchNo = field.NewString(tableName, "mch_no")
	_tradeStatistic.StatisticDate = field.NewTime(tableName, "statistic_date")
	_tradeStatistic.TotalOrder = field.NewInt64(tableName, "total_order")
	_tradeStatistic.SuccessOrder = field.NewInt64(tableName, "success_order")
	_tradeStatistic.TotalAmount = field.NewInt64(tableName, "total_amount")
	_tradeStatistic.SuccessAmount = field.NewInt64(tableName, "success_amount")
	_tradeStatistic.RefundOrder = field.NewInt64(tableName, "refund_order")
	_tradeStatistic.RefundAmount = field.NewInt64(tableName, "refund_amount")
	_tradeStatistic.CreatedAt = field.NewTime(tableName, "created_at")
	_tradeStatistic.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tradeStatistic.fillFieldMap()

	return _tradeStatistic
}

// tradeStatistic 支付交易数据统计
type tradeStatistic struct {
	tradeStatisticDo tradeStatisticDo

	ALL           field.Asterisk
	ID            field.Int64
	AppNo         field.String // 应用编号
	AccountNo     field.String // 支付账号编号
	MchNo         field.String // 商户编号
	StatisticDate field.Time   // 统计日期
	TotalOrder    field.Int64  // 总支付单
	SuccessOrder  field.Int64  // 成功支付单
	TotalAmount   field.Int64  // 总金额
	SuccessAmount field.Int64  // 成功金额
	RefundOrder   field.Int64  // 退款次数
	RefundAmount  field.Int64  // 退款金额
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (t tradeStatistic) Table(newTableName string) *tradeStatistic {
	t.tradeStatisticDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tradeStatistic) As(alias string) *tradeStatistic {
	t.tradeStatisticDo.DO = *(t.tradeStatisticDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tradeStatistic) updateTableName(table string) *tradeStatistic {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.AppNo = field.NewString(table, "app_no")
	t.AccountNo = field.NewString(table, "account_no")
	t.MchNo = field.NewString(table, "mch_no")
	t.StatisticDate = field.NewTime(table, "statistic_date")
	t.TotalOrder = field.NewInt64(table, "total_order")
	t.SuccessOrder = field.NewInt64(table, "success_order")
	t.TotalAmount = field.NewInt64(table, "total_amount")
	t.SuccessAmount = field.NewInt64(table, "success_amount")
	t.RefundOrder = field.NewInt64(table, "refund_order")
	t.RefundAmount = field.NewInt64(table, "refund_amount")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tradeStatistic) WithContext(ctx context.Context) ITradeStatisticDo {
	return t.tradeStatisticDo.WithContext(ctx)
}

func (t tradeStatistic) TableName() string { return t.tradeStatisticDo.TableName() }

func (t tradeStatistic) Alias() string { return t.tradeStatisticDo.Alias() }

func (t tradeStatistic) Columns(cols ...field.Expr) gen.Columns {
	return t.tradeStatisticDo.Columns(cols...)
}

func (t *tradeStatistic) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tradeStatistic) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["app_no"] = t.AppNo
	t.fieldMap["account_no"] = t.AccountNo
	t.fieldMap["mch_no"] = t.MchNo
	t.fieldMap["statistic_date"] = t.StatisticDate
	t.fieldMap["total_order"] = t.TotalOrder
	t.fieldMap["success_order"] = t.SuccessOrder
	t.fieldMap["total_amount"] = t.TotalAmount
	t.fieldMap["success_amount"] = t.SuccessAmount
	t.fieldMap["refund_order"] = t.RefundOrder
	t.fieldMap["refund_amount"] = t.RefundAmount
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tradeStatistic) clone(db *gorm.DB) tradeStatistic {
	t.tradeStatisticDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tradeStatistic) replaceDB(db *gorm.DB) tradeStatistic {
	t.tradeStatisticDo.ReplaceDB(db)
	return t
}

type tradeStatisticDo struct{ gen.DO }

type ITradeStatisticDo interface {
	gen.SubQuery
	Debug() ITradeStatisticDo
	WithContext(ctx context.Context) ITradeStatisticDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITradeStatisticDo
	WriteDB() ITradeStatisticDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITradeStatisticDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITradeStatisticDo
	Not(conds ...gen.Condition) ITradeStatisticDo
	Or(conds ...gen.Condition) ITradeStatisticDo
	Select(conds ...field.Expr) ITradeStatisticDo
	Where(conds ...gen.Condition) ITradeStatisticDo
	Order(conds ...field.Expr) ITradeStatisticDo
	Distinct(cols ...field.Expr) ITradeStatisticDo
	Omit(cols ...field.Expr) ITradeStatisticDo
	Join(table schema.Tabler, on ...field.Expr) ITradeStatisticDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITradeStatisticDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITradeStatisticDo
	Group(cols ...field.Expr) ITradeStatisticDo
	Having(conds ...gen.Condition) ITradeStatisticDo
	Limit(limit int) ITradeStatisticDo
	Offset(offset int) ITradeStatisticDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeStatisticDo
	Unscoped() ITradeStatisticDo
	Create(values ...*model.TradeStatistic) error
	CreateInBatches(values []*model.TradeStatistic, batchSize int) error
	Save(values ...*model.TradeStatistic) error
	First() (*model.TradeStatistic, error)
	Take() (*model.TradeStatistic, error)
	Last() (*model.TradeStatistic, error)
	Find() ([]*model.TradeStatistic, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TradeStatistic, err error)
	FindInBatches(result *[]*model.TradeStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TradeStatistic) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITradeStatisticDo
	Assign(attrs ...field.AssignExpr) ITradeStatisticDo
	Joins(fields ...field.RelationField) ITradeStatisticDo
	Preload(fields ...field.RelationField) ITradeStatisticDo
	FirstOrInit() (*model.TradeStatistic, error)
	FirstOrCreate() (*model.TradeStatistic, error)
	FindByPage(offset int, limit int) (result []*model.TradeStatistic, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITradeStatisticDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tradeStatisticDo) Debug() ITradeStatisticDo {
	return t.withDO(t.DO.Debug())
}

func (t tradeStatisticDo) WithContext(ctx context.Context) ITradeStatisticDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tradeStatisticDo) ReadDB() ITradeStatisticDo {
	return t.Clauses(dbresolver.Read)
}

func (t tradeStatisticDo) WriteDB() ITradeStatisticDo {
	return t.Clauses(dbresolver.Write)
}

func (t tradeStatisticDo) Session(config *gorm.Session) ITradeStatisticDo {
	return t.withDO(t.DO.Session(config))
}

func (t tradeStatisticDo) Clauses(conds ...clause.Expression) ITradeStatisticDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tradeStatisticDo) Returning(value interface{}, columns ...string) ITradeStatisticDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tradeStatisticDo) Not(conds ...gen.Condition) ITradeStatisticDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tradeStatisticDo) Or(conds ...gen.Condition) ITradeStatisticDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tradeStatisticDo) Select(conds ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tradeStatisticDo) Where(conds ...gen.Condition) ITradeStatisticDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tradeStatisticDo) Order(conds ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tradeStatisticDo) Distinct(cols ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tradeStatisticDo) Omit(cols ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tradeStatisticDo) Join(table schema.Tabler, on ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tradeStatisticDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tradeStatisticDo) RightJoin(table schema.Tabler, on ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tradeStatisticDo) Group(cols ...field.Expr) ITradeStatisticDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tradeStatisticDo) Having(conds ...gen.Condition) ITradeStatisticDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tradeStatisticDo) Limit(limit int) ITradeStatisticDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tradeStatisticDo) Offset(offset int) ITradeStatisticDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tradeStatisticDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITradeStatisticDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tradeStatisticDo) Unscoped() ITradeStatisticDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tradeStatisticDo) Create(values ...*model.TradeStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tradeStatisticDo) CreateInBatches(values []*model.TradeStatistic, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tradeStatisticDo) Save(values ...*model.TradeStatistic) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tradeStatisticDo) First() (*model.TradeStatistic, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeStatistic), nil
	}
}

func (t tradeStatisticDo) Take() (*model.TradeStatistic, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeStatistic), nil
	}
}

func (t tradeStatisticDo) Last() (*model.TradeStatistic, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeStatistic), nil
	}
}

func (t tradeStatisticDo) Find() ([]*model.TradeStatistic, error) {
	result, err := t.DO.Find()
	return result.([]*model.TradeStatistic), err
}

func (t tradeStatisticDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TradeStatistic, err error) {
	buf := make([]*model.TradeStatistic, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tradeStatisticDo) FindInBatches(result *[]*model.TradeStatistic, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tradeStatisticDo) Attrs(attrs ...field.AssignExpr) ITradeStatisticDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tradeStatisticDo) Assign(attrs ...field.AssignExpr) ITradeStatisticDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tradeStatisticDo) Joins(fields ...field.RelationField) ITradeStatisticDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tradeStatisticDo) Preload(fields ...field.RelationField) ITradeStatisticDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tradeStatisticDo) FirstOrInit() (*model.TradeStatistic, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeStatistic), nil
	}
}

func (t tradeStatisticDo) FirstOrCreate() (*model.TradeStatistic, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TradeStatistic), nil
	}
}

func (t tradeStatisticDo) FindByPage(offset int, limit int) (result []*model.TradeStatistic, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tradeStatisticDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tradeStatisticDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tradeStatisticDo) Delete(models ...*model.TradeStatistic) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tradeStatisticDo) withDO(do gen.Dao) *tradeStatisticDo {
	t.DO = *do.(*gen.DO)
	return t
}
