// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/payment.proto

package payment

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Goods struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 商品名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 商品SKU
	Sku string `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	// 商品价格，单位分
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// 商品数量
	Quantity int32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// 商品描述
	Desc          string `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goods) Reset() {
	*x = Goods{}
	mi := &file_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Goods) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goods) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Goods) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Goods) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Goods) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// 订单信息
type Order struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderNo string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 订单金额
	Amount *Amount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// 实付金额
	PayAmount *Amount `protobuf:"bytes,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	// 订单商品
	Goods []*Goods `protobuf:"bytes,4,rep,name=goods,proto3" json:"goods,omitempty"`
	// 订单名称
	Subject string `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	// 订单描述
	Desc          string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Order) GetPayAmount() *Amount {
	if x != nil {
		return x.PayAmount
	}
	return nil
}

func (x *Order) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

func (x *Order) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Order) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

// 应用信息
type ApplicationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	IosPackage     string                 `protobuf:"bytes,3,opt,name=ios_package,json=iosPackage,proto3" json:"ios_package,omitempty"`
	AndroidPackage string                 `protobuf:"bytes,4,opt,name=android_package,json=androidPackage,proto3" json:"android_package,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplicationInfo) Reset() {
	*x = ApplicationInfo{}
	mi := &file_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInfo) ProtoMessage() {}

func (x *ApplicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInfo.ProtoReflect.Descriptor instead.
func (*ApplicationInfo) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationInfo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ApplicationInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ApplicationInfo) GetIosPackage() string {
	if x != nil {
		return x.IosPackage
	}
	return ""
}

func (x *ApplicationInfo) GetAndroidPackage() string {
	if x != nil {
		return x.AndroidPackage
	}
	return ""
}

// 买家信息
type Payer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户在商户的标识
	Unionid string `protobuf:"bytes,1,opt,name=unionid,proto3" json:"unionid,omitempty"`
	// 用户在商户下某个应用的标识
	Openid        string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payer) Reset() {
	*x = Payer{}
	mi := &file_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payer) ProtoMessage() {}

func (x *Payer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payer.ProtoReflect.Descriptor instead.
func (*Payer) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *Payer) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *Payer) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

// 金额
type Amount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分单位，一元为100
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 默认币种 CNY 人民币
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *Amount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type H5 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationInfo *ApplicationInfo       `protobuf:"bytes,1,opt,name=application_info,json=applicationInfo,proto3" json:"application_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *H5) Reset() {
	*x = H5{}
	mi := &file_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *H5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*H5) ProtoMessage() {}

func (x *H5) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use H5.ProtoReflect.Descriptor instead.
func (*H5) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *H5) GetApplicationInfo() *ApplicationInfo {
	if x != nil {
		return x.ApplicationInfo
	}
	return nil
}

type SceneInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端IP
	ClientIp string `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// 设备ID
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// 门店ID
	StoreId       string `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneInfo) Reset() {
	*x = SceneInfo{}
	mi := &file_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneInfo) ProtoMessage() {}

func (x *SceneInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneInfo.ProtoReflect.Descriptor instead.
func (*SceneInfo) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *SceneInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SceneInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SceneInfo) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type SettleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否分账
	ProfitSharing bool `protobuf:"varint,1,opt,name=profit_sharing,json=profitSharing,proto3" json:"profit_sharing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleInfo) Reset() {
	*x = SettleInfo{}
	mi := &file_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleInfo) ProtoMessage() {}

func (x *SettleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleInfo.ProtoReflect.Descriptor instead.
func (*SettleInfo) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{7}
}

func (x *SettleInfo) GetProfitSharing() bool {
	if x != nil {
		return x.ProfitSharing
	}
	return false
}

type PayRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Order  *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Amount *Amount                `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Payer  *Payer                 `protobuf:"bytes,3,opt,name=payer,proto3" json:"payer,omitempty"`
	// 支付跳转地址
	RedirectUrl string `protobuf:"bytes,4,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	// 订单超时时间
	TimeExpire int64 `protobuf:"varint,5,opt,name=time_expire,json=timeExpire,proto3" json:"time_expire,omitempty"`
	// 支付回调地址
	NotifyUrl string `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	// 透传参数 如果请求时传递了该参数，异步通知时将该参数原样返回。
	PassbackParams string      `protobuf:"bytes,7,opt,name=passback_params,json=passbackParams,proto3" json:"passback_params,omitempty"`
	SceneInfo      *SceneInfo  `protobuf:"bytes,8,opt,name=scene_info,json=sceneInfo,proto3" json:"scene_info,omitempty"`
	SettleInfo     *SettleInfo `protobuf:"bytes,9,opt,name=settle_info,json=settleInfo,proto3" json:"settle_info,omitempty"`
	// H5 | JSAPI | NATIVE | APP | 扫码
	PaymentMethod string `protobuf:"bytes,10,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_proto_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PayRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PayRequest) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PayRequest) GetPayer() *Payer {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *PayRequest) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *PayRequest) GetTimeExpire() int64 {
	if x != nil {
		return x.TimeExpire
	}
	return 0
}

func (x *PayRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PayRequest) GetPassbackParams() string {
	if x != nil {
		return x.PassbackParams
	}
	return ""
}

func (x *PayRequest) GetSceneInfo() *SceneInfo {
	if x != nil {
		return x.SceneInfo
	}
	return nil
}

func (x *PayRequest) GetSettleInfo() *SettleInfo {
	if x != nil {
		return x.SettleInfo
	}
	return nil
}

func (x *PayRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type PayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单号
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 交易单号
	TradeNo string `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	// 实付金额
	PayAmount *Amount `protobuf:"bytes,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	// Pending | Success | Fail
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// H5 | JSAPI | NATIVE | APP | 扫码
	PaymentMethod string  `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Action        *Action `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_proto_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{9}
}

func (x *PayResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayResponse) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PayResponse) GetPayAmount() *Amount {
	if x != nil {
		return x.PayAmount
	}
	return nil
}

func (x *PayResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PayResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PayResponse) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

// Action 表示支付动作类型
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Redirect | Qrcode | Prepay
	Action        string            `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Method        string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string            `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Parameters    map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{10}
}

func (x *Action) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Action) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Action) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Action) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Query 查询参数
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单号
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 交易单号
	TradeNo       string `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_proto_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{11}
}

func (x *Query) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Query) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

var File_proto_payment_proto protoreflect.FileDescriptor

const file_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payment.proto\x12\apayment\x1a\x1cgoogle/api/annotations.proto\"s\n" +
	"\x05Goods\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\"\xcf\x01\n" +
	"\x05Order\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12'\n" +
	"\x06amount\x18\x02 \x01(\v2\x0f.payment.AmountR\x06amount\x12.\n" +
	"\n" +
	"pay_amount\x18\x03 \x01(\v2\x0f.payment.AmountR\tpayAmount\x12$\n" +
	"\x05goods\x18\x04 \x03(\v2\x0e.payment.GoodsR\x05goods\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\"\x84\x01\n" +
	"\x0fApplicationInfo\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1f\n" +
	"\vios_package\x18\x03 \x01(\tR\n" +
	"iosPackage\x12'\n" +
	"\x0fandroid_package\x18\x04 \x01(\tR\x0eandroidPackage\"9\n" +
	"\x05Payer\x12\x18\n" +
	"\aunionid\x18\x01 \x01(\tR\aunionid\x12\x16\n" +
	"\x06openid\x18\x02 \x01(\tR\x06openid\":\n" +
	"\x06Amount\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"I\n" +
	"\x02H5\x12C\n" +
	"\x10application_info\x18\x01 \x01(\v2\x18.payment.ApplicationInfoR\x0fapplicationInfo\"`\n" +
	"\tSceneInfo\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bstore_id\x18\x03 \x01(\tR\astoreId\"3\n" +
	"\n" +
	"SettleInfo\x12%\n" +
	"\x0eprofit_sharing\x18\x01 \x01(\bR\rprofitSharing\"\x9d\x03\n" +
	"\n" +
	"PayRequest\x12$\n" +
	"\x05order\x18\x01 \x01(\v2\x0e.payment.OrderR\x05order\x12'\n" +
	"\x06amount\x18\x02 \x01(\v2\x0f.payment.AmountR\x06amount\x12$\n" +
	"\x05payer\x18\x03 \x01(\v2\x0e.payment.PayerR\x05payer\x12!\n" +
	"\fredirect_url\x18\x04 \x01(\tR\vredirectUrl\x12\x1f\n" +
	"\vtime_expire\x18\x05 \x01(\x03R\n" +
	"timeExpire\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x06 \x01(\tR\tnotifyUrl\x12'\n" +
	"\x0fpassback_params\x18\a \x01(\tR\x0epassbackParams\x121\n" +
	"\n" +
	"scene_info\x18\b \x01(\v2\x12.payment.SceneInfoR\tsceneInfo\x124\n" +
	"\vsettle_info\x18\t \x01(\v2\x13.payment.SettleInfoR\n" +
	"settleInfo\x12%\n" +
	"\x0epayment_method\x18\n" +
	" \x01(\tR\rpaymentMethod\"\xdb\x01\n" +
	"\vPayResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12.\n" +
	"\n" +
	"pay_amount\x18\x03 \x01(\v2\x0f.payment.AmountR\tpayAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12'\n" +
	"\x06action\x18\x06 \x01(\v2\x0f.payment.ActionR\x06action\"\xca\x01\n" +
	"\x06Action\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12?\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x1f.payment.Action.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x05Query\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo2[\n" +
	"\aPayment\x12P\n" +
	"\x03Pay\x12\x13.payment.PayRequest\x1a\x14.payment.PayResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/payment/payB\vZ\t./paymentb\x06proto3"

var (
	file_proto_payment_proto_rawDescOnce sync.Once
	file_proto_payment_proto_rawDescData []byte
)

func file_proto_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)))
	})
	return file_proto_payment_proto_rawDescData
}

var file_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_payment_proto_goTypes = []any{
	(*Goods)(nil),           // 0: payment.Goods
	(*Order)(nil),           // 1: payment.Order
	(*ApplicationInfo)(nil), // 2: payment.ApplicationInfo
	(*Payer)(nil),           // 3: payment.Payer
	(*Amount)(nil),          // 4: payment.Amount
	(*H5)(nil),              // 5: payment.H5
	(*SceneInfo)(nil),       // 6: payment.SceneInfo
	(*SettleInfo)(nil),      // 7: payment.SettleInfo
	(*PayRequest)(nil),      // 8: payment.PayRequest
	(*PayResponse)(nil),     // 9: payment.PayResponse
	(*Action)(nil),          // 10: payment.Action
	(*Query)(nil),           // 11: payment.Query
	nil,                     // 12: payment.Action.ParametersEntry
}
var file_proto_payment_proto_depIdxs = []int32{
	4,  // 0: payment.Order.amount:type_name -> payment.Amount
	4,  // 1: payment.Order.pay_amount:type_name -> payment.Amount
	0,  // 2: payment.Order.goods:type_name -> payment.Goods
	2,  // 3: payment.H5.application_info:type_name -> payment.ApplicationInfo
	1,  // 4: payment.PayRequest.order:type_name -> payment.Order
	4,  // 5: payment.PayRequest.amount:type_name -> payment.Amount
	3,  // 6: payment.PayRequest.payer:type_name -> payment.Payer
	6,  // 7: payment.PayRequest.scene_info:type_name -> payment.SceneInfo
	7,  // 8: payment.PayRequest.settle_info:type_name -> payment.SettleInfo
	4,  // 9: payment.PayResponse.pay_amount:type_name -> payment.Amount
	10, // 10: payment.PayResponse.action:type_name -> payment.Action
	12, // 11: payment.Action.parameters:type_name -> payment.Action.ParametersEntry
	8,  // 12: payment.Payment.Pay:input_type -> payment.PayRequest
	9,  // 13: payment.Payment.Pay:output_type -> payment.PayResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_payment_proto_init() }
func file_proto_payment_proto_init() {
	if File_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_proto = out.File
	file_proto_payment_proto_goTypes = nil
	file_proto_payment_proto_depIdxs = nil
}
