// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/refund.proto

package refund

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query 查询参数
type RefundQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单号
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 交易单号
	TradeNo       string `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundQuery) Reset() {
	*x = RefundQuery{}
	mi := &file_proto_refund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundQuery) ProtoMessage() {}

func (x *RefundQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_refund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundQuery.ProtoReflect.Descriptor instead.
func (*RefundQuery) Descriptor() ([]byte, []int) {
	return file_proto_refund_proto_rawDescGZIP(), []int{0}
}

func (x *RefundQuery) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundQuery) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type RefundResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单号
	OrderNo string `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	// 退款单号
	RefundNo string `protobuf:"bytes,2,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	// 退款金额
	RefundAmount *Amount `protobuf:"bytes,3,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"`
	// 退款状态
	Status        int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_proto_refund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_refund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_proto_refund_proto_rawDescGZIP(), []int{1}
}

func (x *RefundResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *RefundResponse) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundResponse) GetRefundAmount() *Amount {
	if x != nil {
		return x.RefundAmount
	}
	return nil
}

func (x *RefundResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 金额
type Amount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分单位，一元为100
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// 默认币种 CNY 人民币
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_proto_refund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_refund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_proto_refund_proto_rawDescGZIP(), []int{2}
}

func (x *Amount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_refund_proto protoreflect.FileDescriptor

const file_proto_refund_proto_rawDesc = "" +
	"\n" +
	"\x12proto/refund.proto\x12\x06refund\x1a\x1cgoogle/api/annotations.proto\"C\n" +
	"\vRefundQuery\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\"\x95\x01\n" +
	"\x0eRefundResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1b\n" +
	"\trefund_no\x18\x02 \x01(\tR\brefundNo\x123\n" +
	"\rrefund_amount\x18\x03 \x01(\v2\x0e.refund.AmountR\frefundAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\":\n" +
	"\x06Amount\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency2V\n" +
	"\x06Refund\x12L\n" +
	"\x05Query\x12\x13.refund.RefundQuery\x1a\x16.refund.RefundResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/refundB\n" +
	"Z\b./refundb\x06proto3"

var (
	file_proto_refund_proto_rawDescOnce sync.Once
	file_proto_refund_proto_rawDescData []byte
)

func file_proto_refund_proto_rawDescGZIP() []byte {
	file_proto_refund_proto_rawDescOnce.Do(func() {
		file_proto_refund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_refund_proto_rawDesc), len(file_proto_refund_proto_rawDesc)))
	})
	return file_proto_refund_proto_rawDescData
}

var file_proto_refund_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_refund_proto_goTypes = []any{
	(*RefundQuery)(nil),    // 0: refund.RefundQuery
	(*RefundResponse)(nil), // 1: refund.RefundResponse
	(*Amount)(nil),         // 2: refund.Amount
}
var file_proto_refund_proto_depIdxs = []int32{
	2, // 0: refund.RefundResponse.refund_amount:type_name -> refund.Amount
	0, // 1: refund.Refund.Query:input_type -> refund.RefundQuery
	1, // 2: refund.Refund.Query:output_type -> refund.RefundResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_refund_proto_init() }
func file_proto_refund_proto_init() {
	if File_proto_refund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_refund_proto_rawDesc), len(file_proto_refund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_refund_proto_goTypes,
		DependencyIndexes: file_proto_refund_proto_depIdxs,
		MessageInfos:      file_proto_refund_proto_msgTypes,
	}.Build()
	File_proto_refund_proto = out.File
	file_proto_refund_proto_goTypes = nil
	file_proto_refund_proto_depIdxs = nil
}
