// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/refund.proto

package refund

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Refund_Query_FullMethodName = "/refund.Refund/Query"
)

// RefundClient is the client API for Refund service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RefundClient interface {
	Query(ctx context.Context, in *RefundQuery, opts ...grpc.CallOption) (*RefundResponse, error)
}

type refundClient struct {
	cc grpc.ClientConnInterface
}

func NewRefundClient(cc grpc.ClientConnInterface) RefundClient {
	return &refundClient{cc}
}

func (c *refundClient) Query(ctx context.Context, in *RefundQuery, opts ...grpc.CallOption) (*RefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResponse)
	err := c.cc.Invoke(ctx, Refund_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RefundServer is the server API for Refund service.
// All implementations must embed UnimplementedRefundServer
// for forward compatibility.
type RefundServer interface {
	Query(context.Context, *RefundQuery) (*RefundResponse, error)
	mustEmbedUnimplementedRefundServer()
}

// UnimplementedRefundServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRefundServer struct{}

func (UnimplementedRefundServer) Query(context.Context, *RefundQuery) (*RefundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRefundServer) mustEmbedUnimplementedRefundServer() {}
func (UnimplementedRefundServer) testEmbeddedByValue()                {}

// UnsafeRefundServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RefundServer will
// result in compilation errors.
type UnsafeRefundServer interface {
	mustEmbedUnimplementedRefundServer()
}

func RegisterRefundServer(s grpc.ServiceRegistrar, srv RefundServer) {
	// If the following call pancis, it indicates UnimplementedRefundServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Refund_ServiceDesc, srv)
}

func _Refund_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefundServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Refund_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefundServer).Query(ctx, req.(*RefundQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Refund_ServiceDesc is the grpc.ServiceDesc for Refund service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Refund_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "refund.Refund",
	HandlerType: (*RefundServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Refund_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/refund.proto",
}
