// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: payment.proto

package server

import (
	"context"

	"github.com/lihongsheng/pay-gateway/internal/logic"
	"github.com/lihongsheng/pay-gateway/internal/svc"
	"github.com/lihongsheng/pay-gateway/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) Pay(ctx context.Context, in *payment.PayRequest) (*payment.PayResponse, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}
