// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: refund.proto

package server

import (
	"context"

	"github.com/lihongsheng/pay-gateway/internal/logic"
	"github.com/lihongsheng/pay-gateway/internal/svc"
	"github.com/lihongsheng/pay-gateway/refund"
)

type RefundServer struct {
	svcCtx *svc.ServiceContext
	refund.UnimplementedRefundServer
}

func NewRefundServer(svcCtx *svc.ServiceContext) *RefundServer {
	return &RefundServer{
		svcCtx: svcCtx,
	}
}

func (s *RefundServer) Query(ctx context.Context, in *refund.RefundQuery) (*refund.RefundResponse, error) {
	l := logic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}
