// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: enum/pay.proto

// 定义包名

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付
type Payment int32

const (
	Payment_Payment_UNKNOWN Payment = 0
	// 支付宝
	Payment_Alipay Payment = 1
	// 微信
	Payment_Wxpay Payment = 2
	// 富有
	Payment_Fuiou Payment = 3
)

// Enum value maps for Payment.
var (
	Payment_name = map[int32]string{
		0: "Payment_UNKNOWN",
		1: "Alipay",
		2: "Wxpay",
		3: "Fuiou",
	}
	Payment_value = map[string]int32{
		"Payment_UNKNOWN": 0,
		"Alipay":          1,
		"Wxpay":           2,
		"Fuiou":           3,
	}
)

func (x Payment) Enum() *Payment {
	p := new(Payment)
	*p = x
	return p
}

func (x Payment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Payment) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_pay_proto_enumTypes[0].Descriptor()
}

func (Payment) Type() protoreflect.EnumType {
	return &file_enum_pay_proto_enumTypes[0]
}

func (x Payment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Payment.Descriptor instead.
func (Payment) EnumDescriptor() ([]byte, []int) {
	return file_enum_pay_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PaymentMethod_UNKNOWN PaymentMethod = 0
	// H5
	PaymentMethod_H5 PaymentMethod = 1
	// APP
	PaymentMethod_APP PaymentMethod = 2
	// JSAPI
	PaymentMethod_JSAPI PaymentMethod = 3
	// 原生支付
	PaymentMethod_Native PaymentMethod = 4
	// 人脸支付
	PaymentMethod_Face PaymentMethod = 5
	// 扫码
	PaymentMethod_Qrcode PaymentMethod = 6
	// 设备扫码
	PaymentMethod_Scan PaymentMethod = 7
	// 小程序
	PaymentMethod_LITE PaymentMethod = 8
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PaymentMethod_UNKNOWN",
		1: "H5",
		2: "APP",
		3: "JSAPI",
		4: "Native",
		5: "Face",
		6: "Qrcode",
		7: "Scan",
		8: "LITE",
	}
	PaymentMethod_value = map[string]int32{
		"PaymentMethod_UNKNOWN": 0,
		"H5":                    1,
		"APP":                   2,
		"JSAPI":                 3,
		"Native":                4,
		"Face":                  5,
		"Qrcode":                6,
		"Scan":                  7,
		"LITE":                  8,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_pay_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_enum_pay_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_enum_pay_proto_rawDescGZIP(), []int{1}
}

type Currency int32

const (
	Currency_Currency_UNKNOWN Currency = 0
	Currency_CNY              Currency = 1
	Currency_USD              Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Currency_UNKNOWN",
		1: "CNY",
		2: "USD",
	}
	Currency_value = map[string]int32{
		"Currency_UNKNOWN": 0,
		"CNY":              1,
		"USD":              2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_pay_proto_enumTypes[2].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_enum_pay_proto_enumTypes[2]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_enum_pay_proto_rawDescGZIP(), []int{2}
}

var File_enum_pay_proto protoreflect.FileDescriptor

const file_enum_pay_proto_rawDesc = "" +
	"\n" +
	"\x0eenum/pay.proto\x12\x04enum*@\n" +
	"\aPayment\x12\x13\n" +
	"\x0fPayment_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06Alipay\x10\x01\x12\t\n" +
	"\x05Wxpay\x10\x02\x12\t\n" +
	"\x05Fuiou\x10\x03*|\n" +
	"\rPaymentMethod\x12\x19\n" +
	"\x15PaymentMethod_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02H5\x10\x01\x12\a\n" +
	"\x03APP\x10\x02\x12\t\n" +
	"\x05JSAPI\x10\x03\x12\n" +
	"\n" +
	"\x06Native\x10\x04\x12\b\n" +
	"\x04Face\x10\x05\x12\n" +
	"\n" +
	"\x06Qrcode\x10\x06\x12\b\n" +
	"\x04Scan\x10\a\x12\b\n" +
	"\x04LITE\x10\b*2\n" +
	"\bCurrency\x12\x14\n" +
	"\x10Currency_UNKNOWN\x10\x00\x12\a\n" +
	"\x03CNY\x10\x01\x12\a\n" +
	"\x03USD\x10\x02B\bZ\x06./enumb\x06proto3"

var (
	file_enum_pay_proto_rawDescOnce sync.Once
	file_enum_pay_proto_rawDescData []byte
)

func file_enum_pay_proto_rawDescGZIP() []byte {
	file_enum_pay_proto_rawDescOnce.Do(func() {
		file_enum_pay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_pay_proto_rawDesc), len(file_enum_pay_proto_rawDesc)))
	})
	return file_enum_pay_proto_rawDescData
}

var file_enum_pay_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_enum_pay_proto_goTypes = []any{
	(Payment)(0),       // 0: enum.Payment
	(PaymentMethod)(0), // 1: enum.PaymentMethod
	(Currency)(0),      // 2: enum.Currency
}
var file_enum_pay_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_pay_proto_init() }
func file_enum_pay_proto_init() {
	if File_enum_pay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_pay_proto_rawDesc), len(file_enum_pay_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_pay_proto_goTypes,
		DependencyIndexes: file_enum_pay_proto_depIdxs,
		EnumInfos:         file_enum_pay_proto_enumTypes,
	}.Build()
	File_enum_pay_proto = out.File
	file_enum_pay_proto_goTypes = nil
	file_enum_pay_proto_depIdxs = nil
}
