// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: refund.proto

package refundclient

import (
	"context"

	"github.com/lihongsheng/pay-gateway/refund"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Amount         = refund.Amount
	RefundQuery    = refund.RefundQuery
	RefundResponse = refund.RefundResponse

	Refund interface {
		Query(ctx context.Context, in *RefundQuery, opts ...grpc.CallOption) (*RefundResponse, error)
	}

	defaultRefund struct {
		cli zrpc.Client
	}
)

func NewRefund(cli zrpc.Client) Refund {
	return &defaultRefund{
		cli: cli,
	}
}

func (m *defaultRefund) Query(ctx context.Context, in *RefundQuery, opts ...grpc.CallOption) (*RefundResponse, error) {
	client := refund.NewRefundClient(m.cli.Conn())
	return client.Query(ctx, in, opts...)
}
