// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: errors/error.proto

// 定义包名

package errors

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 重复请求
	ErrorReason_DUPLICATE_REQUEST ErrorReason = 0
	// 为某个枚举单独设置错误码业务错误
	ErrorReason_UNAUTHORIZED    ErrorReason = 1
	ErrorReason_FORBIDDEN       ErrorReason = 2
	ErrorReason_NOT_FOUND       ErrorReason = 3
	ErrorReason_NOT_ACCEPTABLE  ErrorReason = 4
	ErrorReason_INVALID_REQUEST ErrorReason = 5
	ErrorReason_LIMITED         ErrorReason = 6
	ErrorReason_SYSTEM_ERROR    ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "DUPLICATE_REQUEST",
		1: "UNAUTHORIZED",
		2: "FORBIDDEN",
		3: "NOT_FOUND",
		4: "NOT_ACCEPTABLE",
		5: "INVALID_REQUEST",
		6: "LIMITED",
		7: "SYSTEM_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"DUPLICATE_REQUEST": 0,
		"UNAUTHORIZED":      1,
		"FORBIDDEN":         2,
		"NOT_FOUND":         3,
		"NOT_ACCEPTABLE":    4,
		"INVALID_REQUEST":   5,
		"LIMITED":           6,
		"SYSTEM_ERROR":      7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errors_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errors_error_proto_rawDescGZIP(), []int{0}
}

var File_errors_error_proto protoreflect.FileDescriptor

const file_errors_error_proto_rawDesc = "" +
	"\n" +
	"\x12errors/error.proto\x12\tpkg.error\x1a\x13errors/errors.proto*\xd2\x01\n" +
	"\vErrorReason\x12\x1b\n" +
	"\x11DUPLICATE_REQUEST\x10\x00\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fUNAUTHORIZED\x10\x01\x1a\x04\xa8E\x91\x03\x12\x13\n" +
	"\tFORBIDDEN\x10\x02\x1a\x04\xa8E\x93\x03\x12\x13\n" +
	"\tNOT_FOUND\x10\x03\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\x0eNOT_ACCEPTABLE\x10\x04\x1a\x04\xa8E\x94\x03\x12\x19\n" +
	"\x0fINVALID_REQUEST\x10\x05\x1a\x04\xa8E\x9b\x03\x12\x11\n" +
	"\aLIMITED\x10\x06\x1a\x04\xa8E\xad\x03\x12\x16\n" +
	"\fSYSTEM_ERROR\x10\a\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B\vZ\t./errors;b\x06proto3"

var (
	file_errors_error_proto_rawDescOnce sync.Once
	file_errors_error_proto_rawDescData []byte
)

func file_errors_error_proto_rawDescGZIP() []byte {
	file_errors_error_proto_rawDescOnce.Do(func() {
		file_errors_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_error_proto_rawDesc), len(file_errors_error_proto_rawDesc)))
	})
	return file_errors_error_proto_rawDescData
}

var file_errors_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: pkg.error.ErrorReason
}
var file_errors_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_error_proto_init() }
func file_errors_error_proto_init() {
	if File_errors_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_error_proto_rawDesc), len(file_errors_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_error_proto_goTypes,
		DependencyIndexes: file_errors_error_proto_depIdxs,
		EnumInfos:         file_errors_error_proto_enumTypes,
	}.Build()
	File_errors_error_proto = out.File
	file_errors_error_proto_goTypes = nil
	file_errors_error_proto_depIdxs = nil
}
