// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "application"

// Application 公司信息
type Application struct {
	ID               int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	AppName          string    `gorm:"column:app_name;type:varchar(100);not null;comment:应用名字" json:"app_name"`                     // 应用名字
	Secret           string    `gorm:"column:secret;type:varchar(32);not null;comment:应用秘密" json:"secret"`                          // 应用秘密
	AppNo            string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`                         // 应用编号
	MchNo            string    `gorm:"column:mch_no;type:varchar(100);not null;comment:商户编号" json:"mch_no"`                         // 商户编号
	Desc             string    `gorm:"column:desc;type:varchar(255);not null;comment:应用描述" json:"desc"`                             // 应用描述
	PaymentTitle     string    `gorm:"column:payment_title;type:varchar(100);not null;comment:支付的tiltle" json:"payment_title"`      // 支付的tiltle
	PayIcon          string    `gorm:"column:pay_icon;type:varchar(200);not null;comment:支付的icon" json:"pay_icon"`                  // 支付的icon
	Status           int64     `gorm:"column:status;type:tinyint;not null;comment:2 停用 1 正常" json:"status"`                         // 2 停用 1 正常
	IsCustomerDomain int64     `gorm:"column:is_customer_domain;type:tinyint;not null;comment:是否自定义域名方式" json:"is_customer_domain"` // 是否自定义域名方式
	CustomerDomain   string    `gorm:"column:customer_domain;type:varchar(100);not null;comment:自定义域名" json:"customer_domain"`      // 自定义域名
	ProxyHost        string    `gorm:"column:proxy_host;type:varchar(100);not null" json:"proxy_host"`
	ProxyPort        int64     `gorm:"column:proxy_port;type:int;not null;comment:端口" json:"proxy_port"`                                                   // 端口
	ProxyUser        string    `gorm:"column:proxy_user;type:varchar(100);not null;comment:用户名" json:"proxy_user"`                                         // 用户名
	ProxyPwd         string    `gorm:"column:proxy_pwd;type:varchar(100);not null;comment:密码" json:"proxy_pwd"`                                            // 密码
	MultiChannel     int64     `gorm:"column:multi_channel;type:tinyint;not null;comment:是否支持单一channel配置多个" json:"multi_channel"`                          // 是否支持单一channel配置多个
	AccountVersion   string    `gorm:"column:account_version;type:varchar(32);not null;comment:支付账户版本号，每次payment_account都会更新更改版本号" json:"account_version"` // 支付账户版本号，每次payment_account都会更新更改版本号
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
