// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventProcessRecord = "event_process_record"

// EventProcessRecord 支付事件处理记录表
type EventProcessRecord struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	EventID     string    `gorm:"column:event_id;type:varchar(100);not null;comment:事件唯一ID" json:"event_id"`     // 事件唯一ID
	EventType   string    `gorm:"column:event_type;type:varchar(100);not null;comment:事件唯一ID" json:"event_type"` // 事件唯一ID
	ProcessedAt int64     `gorm:"column:processed_at;type:bigint;comment:处理时间,时间戳" json:"processed_at"`          // 处理时间,时间戳
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	Consumer    string    `gorm:"column:consumer;type:varchar(100);not null;comment:消费者" json:"consumer"` // 消费者
}

// TableName EventProcessRecord's table name
func (*EventProcessRecord) TableName() string {
	return TableNameEventProcessRecord
}
