// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotifyRecord = "notify_record"

// NotifyRecord 商户通知记录表,定时任务定期删除7天之前的数据
type NotifyRecord struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:商户通知记录ID" json:"id"`            // 商户通知记录ID
	NotifyType     int64     `gorm:"column:notify_type;type:tinyint;not null;comment:类型:1-支付,2-退款，3转账" json:"notify_type"`      // 类型:1-支付,2-退款，3转账
	AppNo          string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`                       // 应用编号
	MchNo          string    `gorm:"column:mch_no;type:varchar(100);not null;comment:公司编号" json:"mch_no"`                       // 公司编号
	Resaon         string    `gorm:"column:resaon;type:varchar(255);not null;comment:描述" json:"resaon"`                         // 描述
	OutNo          string    `gorm:"column:out_no;type:varchar(64);not null;comment:订单号或者退款号" json:"out_no"`                    // 订单号或者退款号
	TradeNo        string    `gorm:"column:trade_no;type:varchar(100);not null;comment:支付系统交易号" json:"trade_no"`                // 支付系统交易号
	NotifyURL      string    `gorm:"column:notify_url;type:varchar(255);not null;comment:通知地址" json:"notify_url"`               // 通知地址
	ResResult      string    `gorm:"column:res_result;type:varchar(200);comment:通知响应结果" json:"res_result"`                      // 通知响应结果
	NotifyCount    int64     `gorm:"column:notify_count;type:int;not null;comment:通知次数" json:"notify_count"`                    // 通知次数
	NotifyStatus   int64     `gorm:"column:notify_status;type:tinyint;not null;comment:1待通知， 2已通知 3 通知失败" json:"notify_status"` // 1待通知， 2已通知 3 通知失败
	LastNotifyTime time.Time `gorm:"column:last_notify_time;type:datetime;comment:最后一次通知时间" json:"last_notify_time"`            // 最后一次通知时间
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName NotifyRecord's table name
func (*NotifyRecord) TableName() string {
	return TableNameNotifyRecord
}
