// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentAccount = "payment_account"

// PaymentAccount 支付主体账号
type PaymentAccount struct {
	ID             int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;type:varchar(100);not null;comment:名字标识" json:"name"`                                                     // 名字标识
	Remark         string    `gorm:"column:remark;type:varchar(200);not null;comment:描述" json:"remark"`                                                   // 描述
	AppNo          string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`                                                 // 应用编号
	MchNo          string    `gorm:"column:mch_no;type:varchar(100);not null;comment:商户编号" json:"mch_no"`                                                 // 商户编号
	Channel        string    `gorm:"column:channel;type:varchar(60);not null;comment:支付渠道：Wechat 微信 | Alipay 支付宝 | Lakala 拉卡拉 | Fuiou 富有" json:"channel"` // 支付渠道：Wechat 微信 | Alipay 支付宝 | Lakala 拉卡拉 | Fuiou 富有
	Status         int64     `gorm:"column:status;type:tinyint;not null;default:1;comment:2 停用 1 正常" json:"status"`                                       // 2 停用 1 正常
	Extend         string    `gorm:"column:extend;type:json;not null;comment:拓展配置" json:"extend"`                                                         // 拓展配置
	MaxLimit       int64     `gorm:"column:max_limit;type:int;not null;comment:单日最大支付次数" json:"max_limit"`                                                // 单日最大支付次数
	ValidateStatus int64     `gorm:"column:validate_status;type:tinyint;not null;comment:是否验证 0 没有 1 验证通过" json:"validate_status"`                        // 是否验证 0 没有 1 验证通过
	AccountNo      string    `gorm:"column:account_no;type:varchar(100);not null;comment:账户编号" json:"account_no"`                                         // 账户编号
	ChannelConfig  string    `gorm:"column:channel_config;type:json;not null;comment:各个渠道的私有配置" json:"channel_config"`                                    // 各个渠道的私有配置
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	PaymentMethod  []*PaymentMethod`gorm:"foreignKey:PaymentAccountID;references:ID" json:"payment_method"`
}

// TableName PaymentAccount's table name
func (*PaymentAccount) TableName() string {
	return TableNamePaymentAccount
}
