// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentExpireRecord = "payment_expire_record"

// PaymentExpireRecord 支付过期记录表,定时任务定期删除1天之前的数据
type PaymentExpireRecord struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`   // ID
	AppNo      string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`        // 应用编号
	MchNo      string    `gorm:"column:mch_no;type:varchar(100);not null;comment:公司编号" json:"mch_no"`        // 公司编号
	OrderNo    string    `gorm:"column:order_no;type:varchar(64);not null;comment:订单号号" json:"order_no"`     // 订单号号
	TradeNo    string    `gorm:"column:trade_no;type:varchar(100);not null;comment:支付系统交易号" json:"trade_no"` // 支付系统交易号
	ExpireTime time.Time `gorm:"column:expire_time;type:datetime;comment:过期时间" json:"expire_time"`           // 过期时间
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PaymentExpireRecord's table name
func (*PaymentExpireRecord) TableName() string {
	return TableNamePaymentExpireRecord
}
