// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentMethod = "payment_method"

// PaymentMethod 支付方式
type PaymentMethod struct {
	ID               int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	PaymentAccountID int64     `gorm:"column:payment_account_id;type:int;not null;comment:payemnt_account_id表自增id" json:"payment_account_id"`                        // payemnt_account_id表自增id
	PaymentMethod    string    `gorm:"column:payment_method;type:varchar(60);not null;comment:支付方式：Wechat 微信 | Alipay 支付宝 | 云闪付" json:"payment_method"`              // 支付方式：Wechat 微信 | Alipay 支付宝 | 云闪付
	PaymentProduct   string    `gorm:"column:payment_product;type:varchar(60);not null;comment:支付产品：H5 | JSAPI | LITE | APP | Qrcode | Card" json:"payment_product"` // 支付产品：H5 | JSAPI | LITE | APP | Qrcode | Card
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PaymentMethod's table name
func (*PaymentMethod) TableName() string {
	return TableNamePaymentMethod
}
