// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentRequestLog = "payment_request_log"

// PaymentRequestLog 请求日志
type PaymentRequestLog struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Request   string    `gorm:"column:request;type:json;comment:请求body" json:"request"`                     // 请求body
	Response  string    `gorm:"column:response;type:json;comment:返回body" json:"response"`                   // 返回body
	OrderNo   string    `gorm:"column:order_no;type:varchar(64);not null;comment:订单号" json:"order_no"`      // 订单号
	TradeNo   string    `gorm:"column:trade_no;type:varchar(100);not null;comment:支付系统交易号" json:"trade_no"` // 支付系统交易号
	MchNo     string    `gorm:"column:mch_no;type:varchar(100);not null" json:"mch_no"`
	AppNo     string    `gorm:"column:app_no;type:varchar(100);not null" json:"app_no"`
	RequestID string    `gorm:"column:request_id;type:varchar(100);not null;comment:请求ID" json:"request_id"` // 请求ID
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName PaymentRequestLog's table name
func (*PaymentRequestLog) TableName() string {
	return TableNamePaymentRequestLog
}
