// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePaymentOrderProduct = "payment_order_product"

// PaymentOrderProduct 支付产品表
type PaymentOrderProduct struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ProductName string    `gorm:"column:product_name;type:varchar(100);not null;comment:订单标题" json:"product_name"` // 订单标题
	AppNo       string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`             // 应用编号
	MchNo       string    `gorm:"column:mch_no;type:varchar(100);primaryKey;comment:商户编号" json:"mch_no"`           // 商户编号
	Quantity    int64     `gorm:"column:quantity;type:int;not null;comment:购买数量" json:"quantity"`                  // 购买数量
	Price       int64     `gorm:"column:price;type:int;not null;comment:单价" json:"price"`                          // 单价
	Sku         string    `gorm:"column:sku;type:varchar(100);not null;comment:商品sku" json:"sku"`                  // 商品sku
	ProductDesc string    `gorm:"column:product_desc;type:varchar(255);not null;comment:商品描述" json:"product_desc"` // 商品描述
	URL         string    `gorm:"column:url;type:varchar(255);not null;comment:商品链接" json:"url"`                   // 商品链接
	OrderNo     string    `gorm:"column:order_no;type:varchar(64);not null;comment:订单号" json:"order_no"`           // 订单号
	TradeNo     string    `gorm:"column:trade_no;type:varchar(100);not null;comment:支付单号" json:"trade_no"`         // 支付单号
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;primaryKey;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PaymentOrderProduct's table name
func (*PaymentOrderProduct) TableName() string {
	return TableNamePaymentOrderProduct
}
