// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefundOrderProduct = "refund_order_product"

// RefundOrderProduct 退款详情
type RefundOrderProduct struct {
	ID        int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;type:varchar(100);not null;comment:订单标题" json:"name"`              // 订单标题
	Quantity  int64     `gorm:"column:quantity;type:int;not null;comment:购买数量" json:"quantity"`               // 购买数量
	Price     int64     `gorm:"column:price;type:bigint;not null;comment:单价" json:"price"`                    // 单价
	Sku       string    `gorm:"column:sku;type:varchar(64);not null;comment:商品sku" json:"sku"`                // 商品sku
	Desc      string    `gorm:"column:desc;type:varchar(100);not null;comment:商品描述" json:"desc"`              // 商品描述
	URL       string    `gorm:"column:url;type:varchar(255);not null;comment:商品链接" json:"url"`                // 商品链接
	OrderNo   string    `gorm:"column:order_no;type:varchar(64);not null;comment:订单号" json:"order_no"`        // 订单号
	RefundNo  string    `gorm:"column:refund_no;type:varchar(100);not null;comment:支付系统交易号" json:"refund_no"` // 支付系统交易号
	CreatedAt time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RefundOrderProduct's table name
func (*RefundOrderProduct) TableName() string {
	return TableNameRefundOrderProduct
}
