// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefundOrder = "refund_order"

// RefundOrder 支付方式
type RefundOrder struct {
	ID               int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	PaymentAccountNo string    `gorm:"column:payment_account_no;type:varchar(64);not null;comment:payemnt_account_no" json:"payment_account_no"` // payemnt_account_no
	AppNo            string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`                                      // 应用编号
	MchNo            string    `gorm:"column:mch_no;type:varchar(100);not null;comment:商户编号" json:"mch_no"`                                      // 商户编号
	Resaon           string    `gorm:"column:resaon;type:varchar(255);not null;comment:退款原因" json:"resaon"`                                      // 退款原因
	OrderNo          string    `gorm:"column:order_no;type:varchar(64);not null;comment:订单号" json:"order_no"`                                    // 订单号
	TradeNo          string    `gorm:"column:trade_no;type:varchar(100);not null;comment:支付系统交易号" json:"trade_no"`                               // 支付系统交易号
	RefundTradeNo    string    `gorm:"column:refund_trade_no;type:varchar(100);not null;comment:渠道退款号" json:"refund_trade_no"`                   // 渠道退款号
	RefundNo         string    `gorm:"column:refund_no;type:varchar(100);not null;comment:支付系统交易号" json:"refund_no"`                             // 支付系统交易号
	Device           string    `gorm:"column:device;type:varchar(100);not null;comment:支付系统交易号" json:"device"`                                   // 支付系统交易号
	RefundAmount     int64     `gorm:"column:refund_amount;type:bigint;not null;comment:退款金额分单位" json:"refund_amount"`                           // 退款金额分单位
	PaymentAmount    int64     `gorm:"column:payment_amount;type:bigint;not null;comment:订单实付金额分单位" json:"payment_amount"`                       // 订单实付金额分单位
	Currency         string    `gorm:"column:currency;type:varchar(10);not null;comment:币种" json:"currency"`                                     // 币种
	Status           int64     `gorm:"column:status;type:tinyint;not null;comment:退款状态" json:"status"`                                           // 退款状态
	StatusFrom       string    `gorm:"column:status_from;type:varchar(100);not null;comment:状态修改来源API|WEBHOOK|ADMIN" json:"status_from"`         // 状态修改来源API|WEBHOOK|ADMIN
	NotifyURL        string    `gorm:"column:notify_url;type:varchar(200);not null;comment:异步通知url" json:"notify_url"`                           // 异步通知url
	NotifyStatus     int64     `gorm:"column:notify_status;type:tinyint;not null;comment:1待通知， 2已通知" json:"notify_status"`                       // 1待通知， 2已通知
	OutMchTradeNo    string    `gorm:"column:out_mch_trade_no;type:varchar(100);not null;comment:外部请求退款单号" json:"out_mch_trade_no"`              // 外部请求退款单号
	ExtParam         string    `gorm:"column:ext_param;type:varchar(255);not null;comment:扩展参数" json:"ext_param"`                                // 扩展参数
	SuccessTime      time.Time `gorm:"column:success_time;type:datetime;comment:成功时间" json:"success_time"`                                       // 成功时间
	RefundFrom       int64     `gorm:"column:refund_from;type:tinyint;not null;default:2;comment:发起 1 外部接口发起，2 后台发起" json:"refund_from"`         // 发起 1 外部接口发起，2 后台发起
	ThirdMsg         string    `gorm:"column:third_msg;type:varchar(200);not null;comment:三方返回错误原因" json:"third_msg"`                            // 三方返回错误原因
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RefundOrder's table name
func (*RefundOrder) TableName() string {
	return TableNameRefundOrder
}
