// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRouterAccountStatistic = "router_account_statistics"

// RouterAccountStatistic 路由需要的数据统计
type RouterAccountStatistic struct {
	ID              int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AppNo           string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`           // 应用编号
	AccountNo       string    `gorm:"column:account_no;type:varchar(100);not null;comment:支付账号编号" json:"account_no"` // 支付账号编号
	StatisticDate   time.Time `gorm:"column:statistic_date;type:date;not null;comment:统计日期" json:"statistic_date"`   // 统计日期
	TotalRequests   int64     `gorm:"column:total_requests;type:int;comment:总请求数" json:"total_requests"`             // 总请求数
	SuccessRequests int64     `gorm:"column:success_requests;type:int;comment:成功请求数" json:"success_requests"`        // 成功请求数
	FailureRequests int64     `gorm:"column:failure_requests;type:int;comment:失败请求数" json:"failure_requests"`        // 失败请求数
	UserLimit       int64     `gorm:"column:user_limit;type:tinyint;comment:用户登录是否限制, 0 未限制，1限制" json:"user_limit"`  // 用户登录是否限制, 0 未限制，1限制
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	SuccessAmount   int64     `gorm:"column:success_amount;type:int;not null;comment:收款金额，分单位" json:"success_amount"`         // 收款金额，分单位
	PaymentLimit    int64     `gorm:"column:payment_limit;type:tinyint;not null;comment:0 未限制，1收款被微信限制" json:"payment_limit"` // 0 未限制，1收款被微信限制
}

// TableName RouterAccountStatistic's table name
func (*RouterAccountStatistic) TableName() string {
	return TableNameRouterAccountStatistic
}
