// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStatistic = "statistics"

// Statistic 数据统计
type Statistic struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AppNo          string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`                // 应用编号
	MchNo          string    `gorm:"column:mch_no;type:varchar(100);not null;comment:商户编号" json:"mch_no"`                // 商户编号
	StatisticDate  time.Time `gorm:"column:statistic_date;type:date;not null;comment:统计日期" json:"statistic_date"`        // 统计日期
	StatisticTag   string    `gorm:"column:statistic_tag;type:varchar(100);comment:标签" json:"statistic_tag"`             // 标签
	StatisticKey   string    `gorm:"column:statistic_key;type:varchar(100);comment:标签下某个统计项" json:"statistic_key"`       // 标签下某个统计项
	StatisticLabel string    `gorm:"column:statistic_label;type:varchar(100);comment:标签下某个统计项名字" json:"statistic_label"` // 标签下某个统计项名字
	Statistic      int64     `gorm:"column:statistic;type:int;comment:统计计数" json:"statistic"`                            // 统计计数
	CreatedAt      time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Statistic's table name
func (*Statistic) TableName() string {
	return TableNameStatistic
}
