// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTradeStatistic = "trade_statistics"

// TradeStatistic 支付交易数据统计
type TradeStatistic struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	AppNo         string    `gorm:"column:app_no;type:varchar(100);not null;comment:应用编号" json:"app_no"`           // 应用编号
	AccountNo     string    `gorm:"column:account_no;type:varchar(100);not null;comment:支付账号编号" json:"account_no"` // 支付账号编号
	MchNo         string    `gorm:"column:mch_no;type:varchar(100);not null;comment:商户编号" json:"mch_no"`           // 商户编号
	StatisticDate time.Time `gorm:"column:statistic_date;type:date;not null;comment:统计日期" json:"statistic_date"`   // 统计日期
	TotalOrder    int64     `gorm:"column:total_order;type:int;comment:总支付单" json:"total_order"`                   // 总支付单
	SuccessOrder  int64     `gorm:"column:success_order;type:int;comment:成功支付单" json:"success_order"`              // 成功支付单
	TotalAmount   int64     `gorm:"column:total_amount;type:bigint;comment:总金额" json:"total_amount"`               // 总金额
	SuccessAmount int64     `gorm:"column:success_amount;type:bigint;comment:成功金额" json:"success_amount"`          // 成功金额
	RefundOrder   int64     `gorm:"column:refund_order;type:int;not null;comment:退款次数" json:"refund_order"`        // 退款次数
	RefundAmount  int64     `gorm:"column:refund_amount;type:bigint;comment:退款金额" json:"refund_amount"`            // 退款金额
	CreatedAt     time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TradeStatistic's table name
func (*TradeStatistic) TableName() string {
	return TableNameTradeStatistic
}
